"""Content for AWS_Interview_Theory.docx.

Resume-aligned: ECS, ECR, App Runner, IAM, ALB are on Sanket's resume, so those
get extra depth - interviewers probe what the resume claims. 3-YOE level,
simple English, CLI/config example per topic.
Run:  python build_docx.py aws
"""

DOC_TITLE = "AWS / Cloud Interview Theory Notes"
DOC_SUBTITLE = "Resume-aligned (ECS, ECR, App Runner, IAM, ALB)  |  3-YOE depth  |  Sanket Kolhe"

CONTENT = [
    {
        "phase": "AWS Phase 1 - Core Concepts",
        "topics": [
            {
                "title": "A1.1  What is AWS - Regions, AZs, Shared Responsibility",
                "what": "AWS is the largest cloud platform - on-demand compute, storage and services, organized into regions made of isolated availability zones.",
                "points": [
                    "Cloud value: no upfront hardware, pay per use, scale up/down in minutes, managed services replace ops work.",
                    "Region = a geographic area (ap-south-1 is Mumbai); AZ = one or more isolated data centers inside it, with independent power/network.",
                    "High availability = running across multiple AZs - an AZ failure does not take the app down. Multi-region is for disaster recovery and global latency.",
                    "Data residency: choosing the region controls where data physically lives (matters for Indian fintech/compliance).",
                    "Shared responsibility model (asked often): AWS secures the cloud (hardware, network, hypervisor); WE secure what is in it (IAM, security groups, patching, data encryption, app code).",
                    "Interact via console, CLI, SDKs (boto3 in Python) and IaC (Terraform/CloudFormation).",
                ],
                "example": "aws configure   # keys + region\naws ec2 describe-availability-zones \\\n  --region ap-south-1\n# ap-south-1a, ap-south-1b, ap-south-1c",
                "answer": "AWS gives on-demand infrastructure and managed services, organized as regions containing isolated AZs - high availability means spreading across AZs, like Mumbai's three. The shared responsibility model splits security: AWS secures the infrastructure, we secure IAM, network rules, data and code. I work with it via CLI, boto3 and CI/CD.",
            },
            {
                "title": "A1.2  IAM - Users, Roles, Policies",
                "what": "IAM controls who can do what in the account - identities (users, roles) get JSON policies granting specific actions on specific resources.",
                "points": [
                    "User = a person/long-term credential; Group = users sharing policies; Role = an identity ASSUMED temporarily - by services, apps or people - with auto-rotating credentials.",
                    "Policy = JSON: Effect (Allow/Deny), Action (s3:GetObject), Resource (ARN), optional Condition. Explicit Deny always wins.",
                    "The key practice: ROLES for apps, never access keys in code. An ECS task role or EC2 instance profile gives the app S3/DB access with no stored secrets - this is what interviewers want to hear.",
                    "Least privilege: grant the minimum actions on the minimum resources - s3:GetObject on one bucket, not s3:* on *.",
                    "Root account: enable MFA, create an admin IAM user, never use root day-to-day, never make root access keys.",
                    "Identity-based policies attach to identities; resource-based (bucket policies) attach to resources; both evaluate together.",
                    "My use: task roles for ECS services, a CI role for Jenkins deploys, scoped user for local dev.",
                ],
                "example": "{\n  \"Effect\": \"Allow\",\n  \"Action\": [\"s3:GetObject\",\n             \"s3:PutObject\"],\n  \"Resource\":\n    \"arn:aws:s3:::mailflow-media/*\"\n}\n# attach to an ECS task ROLE, not keys",
                "answer": "IAM identities get JSON policies - action, resource, effect, with explicit deny winning. The practice that matters: applications use roles (ECS task roles, instance profiles) with temporary auto-rotated credentials, never embedded access keys; humans get least-privilege users with MFA, and root stays locked away. I scope policies to exact actions on exact ARNs.",
            },
            {
                "title": "A1.3  EC2",
                "what": "EC2 is a virtual server - we pick the instance type, an AMI image, attach storage and security groups, and manage it ourselves.",
                "points": [
                    "Instance types: t-family burstable (t3.micro dev), m general, c compute-heavy, r memory-heavy - sized as vCPU + RAM.",
                    "AMI = the machine image (OS + preinstalled stack) an instance boots from; custom AMIs bake our app for fast scaling.",
                    "EBS = network-attached persistent disk, survives stop/start, snapshots to S3 for backup; instance-store is ephemeral.",
                    "Security group = stateful instance-level firewall: allow inbound 443 from anywhere, 22 from office IP only; return traffic auto-allowed.",
                    "Key pairs for SSH - better: SSM Session Manager (no open port 22, audited access) - modern answer.",
                    "User data script runs at first boot (install docker, join cluster).",
                    "EC2 vs managed: EC2 = full control + full patching burden; that trade is why containers/serverless exist.",
                ],
                "example": "aws ec2 run-instances \\\n  --image-id ami-0abcd1234 \\\n  --instance-type t3.small \\\n  --key-name prod-key \\\n  --security-group-ids sg-0123 \\\n  --user-data file://install-docker.sh",
                "answer": "EC2 is IaaS: pick instance family and size, boot from an AMI, attach EBS volumes and a stateful security-group firewall. I know burstable vs compute vs memory families, user-data bootstrap scripts, SSM Session Manager over open SSH, and the trade-off - full control but full patching responsibility, which is why my deployments moved to ECS.",
            },
            {
                "title": "A1.4  S3",
                "what": "S3 is durable object storage - files as objects in globally-unique buckets, accessed by key over HTTP, with storage classes for cost.",
                "points": [
                    "Object storage, not a filesystem: key -> object (up to 5TB) + metadata; 'folders' are just key prefixes.",
                    "11 nines durability - data is replicated across AZs automatically.",
                    "Storage classes: Standard (hot), Standard-IA (infrequent), Glacier tiers (archive) - lifecycle rules auto-move objects (logs to IA at 30 days, Glacier at 90, delete at 365).",
                    "Security: buckets are private by default; Block Public Access stays ON; access via IAM/bucket policies; encryption at rest is default now.",
                    "Presigned URLs: temporary signed links for upload/download - THE pattern for user files (browser uploads direct to S3, app never proxies bytes).",
                    "Versioning protects against overwrite/delete; replication copies cross-region.",
                    "Uses: media files (Django/FastAPI uploads), static hosting, backups, data lake for analytics.",
                ],
                "example": "url = s3.generate_presigned_url(\n  \"put_object\",\n  Params={\"Bucket\": \"mailflow-media\",\n          \"Key\": f\"uploads/{fname}\"},\n  ExpiresIn=300)\n# browser PUTs directly to S3",
                "answer": "S3 stores objects by key in private-by-default buckets with eleven-nines durability, tiered storage classes and lifecycle rules moving data to IA and Glacier over time. My working patterns: IAM-scoped access with Block Public Access on, presigned URLs so clients upload directly without proxying through the app, and versioning for accident protection.",
            },
            {
                "title": "A1.5  VPC Basics",
                "what": "A VPC is our private network in AWS - subnets split it across AZs, route tables and gateways control traffic, SGs and NACLs filter it.",
                "points": [
                    "VPC = an isolated network with a CIDR range (10.0.0.0/16); everything (EC2, ECS, RDS) lives inside one.",
                    "Public subnet: route to an Internet Gateway - load balancers and NAT live here. Private subnet: no direct internet - app containers and databases live here. Standard layout: public + private per AZ.",
                    "NAT Gateway lets private resources reach OUT (pip install, external APIs) while nothing reaches in.",
                    "Security group: stateful, instance-level, allow-only rules - primary tool. NACL: stateless subnet-level allow/deny - rarely customized; the SG-vs-NACL contrast is a favorite question.",
                    "The security pattern: ALB's SG open to the world; app SG allows only from ALB's SG; DB SG allows 5432 only from app SG - SG-referencing chains, no CIDRs.",
                    "VPC endpoints reach S3/AWS APIs privately without internet transit.",
                ],
                "example": "VPC 10.0.0.0/16\n  public-a  10.0.1.0/24  (ALB, NAT)\n  private-a 10.0.11.0/24 (ECS tasks)\n  private-b 10.0.12.0/24 (RDS)\nDB SG: allow 5432 from app-SG only",
                "answer": "A VPC is the private network: public subnets hold the ALB and NAT gateway, private subnets hold app containers and the database, which reach out through NAT but accept nothing inbound. Security groups are stateful allow-lists chained by reference - ALB to app to DB - while NACLs are stateless subnet filters that mostly stay default. That layered layout is my standard deployment.",
            },
            {
                "title": "A1.6  Pricing Model",
                "what": "AWS bills pay-per-use - compute by time, storage by GB-month, data transfer OUT by GB - with discounts for commitment and interruption tolerance.",
                "points": [
                    "On-demand: full price, no commitment - default for unpredictable loads.",
                    "Reserved/Savings Plans: 1-3 year commitment for up to ~70% off - for steady baseline load.",
                    "Spot: spare capacity ~90% off, reclaimable with 2-minute notice - batch jobs, CI runners, fault-tolerant workers; never the only copy of stateful services.",
                    "Data transfer: IN free, OUT to internet billed - and cross-AZ transfer costs too; a favorite surprise-bill source.",
                    "NAT Gateway hourly + per-GB is the classic silent cost; idle provisioned resources (unused EIPs, oversized RDS) are the other.",
                    "Free tier covers t-micro instances, small RDS, S3/Lambda allowances - enough for demos.",
                    "Guardrails: billing alerts + budgets on day one; tags per project/env make bills explainable.",
                ],
                "example": "aws budgets create-budget ... \\\n  --budget '{\"BudgetLimit\":\n    {\"Amount\":\"50\",\"Unit\":\"USD\"},\n    \"TimeUnit\":\"MONTHLY\",\n    \"BudgetType\":\"COST\"}'",
                "answer": "Compute bills by time, storage by GB-month, and egress by GB - transfer out and cross-AZ traffic are the classic surprises, NAT Gateway the classic silent cost. On-demand for spiky load, Savings Plans for the steady baseline, Spot at ~90% off for interruptible work like batch and CI. I set budgets and billing alarms on day one and tag everything.",
            },
        ],
    },
    {
        "phase": "AWS Phase 2 - Compute and Containers (resume core)",
        "topics": [
            {
                "title": "A2.1  Docker Recap - The Interview Angle",
                "what": "Docker packages the app with its whole environment into an image; containers are running instances sharing the host kernel - lighter than VMs.",
                "points": [
                    "Image = immutable layered snapshot (base OS + deps + code); container = a running process with isolated filesystem/network from that image.",
                    "Container vs VM: containers share the host kernel - MBs and milliseconds vs GBs and minutes. Isolation is process-level, not hardware-level.",
                    "Dockerfile best practices interviewers probe: order layers for cache (deps install before code copy), multi-stage builds (build tools out of the final image), slim base images, non-root USER, .dockerignore.",
                    "'Works on my machine' dies: dev, CI and prod run the identical image - the image IS the artifact CI ships.",
                    "Registry flow: build -> tag -> push (ECR) -> pull and run (ECS).",
                    "Compose runs multi-container stacks locally (app + Postgres + Redis) - my dev setup mirror of production.",
                ],
                "example": "FROM python:3.12-slim AS base\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nUSER app\nCMD [\"gunicorn\", \"-k\",\n  \"uvicorn.workers.UvicornWorker\",\n  \"app.main:app\"]",
                "answer": "An image is a layered immutable snapshot; a container is that image running as an isolated process sharing the host kernel - hence lighter and faster than VMs. My Dockerfile answers: dependency layers before code for cache hits, multi-stage builds to slim the runtime image, non-root user, and the image as the single artifact flowing dev -> CI -> ECR -> ECS.",
            },
            {
                "title": "A2.2  ECR - Elastic Container Registry",
                "what": "ECR is AWS's private Docker registry - CI pushes images there, ECS/App Runner pull from there, with IAM controlling both sides.",
                "points": [
                    "Private repositories per app; images addressed as account.dkr.ecr.region.amazonaws.com/repo:tag.",
                    "Auth is IAM-based: get-login-password pipes a temp token into docker login - no permanent registry passwords; CI roles get push rights, task execution roles get pull rights.",
                    "Image scanning flags CVEs on push (basic free, enhanced via Inspector) - a security checkbox interviewers like.",
                    "Lifecycle policies auto-delete old images (keep last 10) - untended repos silently accumulate storage cost.",
                    "Tagging discipline: immutable tags with the git SHA (app:3fa2b91) - :latest deploys are un-rollback-able mysteries; SHA tags make rollback = redeploy previous tag.",
                    "Cross-account/region replication supports multi-env setups.",
                ],
                "example": "aws ecr get-login-password |\n  docker login --username AWS \\\n    --password-stdin $ECR_URI\ndocker build -t $ECR_URI/mailflow:$GIT_SHA .\ndocker push $ECR_URI/mailflow:$GIT_SHA",
                "answer": "ECR is the private registry in the deploy chain: CI authenticates with a temporary IAM token, pushes an image tagged with the git SHA, ECS pulls it via the task execution role. Scan-on-push catches CVEs, lifecycle policies prune old images, and SHA-based immutable tags - never bare :latest - are what make rollbacks a one-line redeploy.",
            },
            {
                "title": "A2.3  ECS - Cluster, Task Definition, Service",
                "what": "ECS is AWS's container orchestrator: a task definition describes containers, a service keeps N copies running behind a load balancer in a cluster.",
                "points": [
                    "Task definition = the versioned JSON blueprint: image, CPU/memory, env vars, secrets, ports, log config. A task = one running copy.",
                    "Service = the supervisor: desired count, replaces crashed tasks, registers them in the ALB target group, rolls new versions gradually.",
                    "Cluster = the logical grouping of capacity (Fargate or EC2 instances).",
                    "Two IAM roles per task - execution role (pull image, write logs, read secrets - infrastructure) vs task role (what YOUR CODE may call - S3, SQS). Interviewers love this distinction.",
                    "Deploy flow: push new image -> register new task definition revision -> service rolling-updates with min/max healthy percent -> ALB health checks gate traffic; circuit breaker auto-rolls-back failed deploys.",
                    "Scaling: service auto scaling on CPU/memory/request-count metrics.",
                    "vs Kubernetes: ECS is simpler and AWS-native (my production use); EKS when the org wants the k8s ecosystem/portability.",
                ],
                "example": "{\n \"family\": \"mailflow-api\",\n \"cpu\": \"512\", \"memory\": \"1024\",\n \"containerDefinitions\": [{\n   \"image\": \"...ecr.../mailflow:3fa2b91\",\n   \"portMappings\": [{\"containerPort\": 8000}],\n   \"secrets\": [{\"name\": \"DB_PASSWORD\",\n     \"valueFrom\": \"arn:aws:ssm:...\"}]\n }]\n}",
                "answer": "ECS runs containers from a versioned task definition - image, resources, env, secrets - while a service keeps the desired count alive behind the ALB and rolls deployments with health-check gating and auto-rollback. Two roles matter: the execution role pulls images and reads secrets, the task role scopes what the app code itself can call. I ran production APIs this way; EKS is the choice when the k8s ecosystem is required.",
            },
            {
                "title": "A2.4  Fargate vs EC2 Launch Type",
                "what": "Fargate runs containers serverless - AWS manages the hosts; EC2 launch type gives us the instances to manage but cheaper at steady scale.",
                "points": [
                    "Fargate: declare CPU/memory per task, AWS finds the compute - no instances to patch, size or scale. Billing per task-second.",
                    "EC2 type: we run the container instances - patching, capacity planning, bin-packing are ours; instance pricing (with reserved/spot discounts) wins at high steady utilization.",
                    "Fargate trade-offs: no GPU (mostly), per-vCPU price premium, no daemonsets/privileged containers, cold task start seconds.",
                    "Choose Fargate: variable load, small teams, no ops appetite - the default answer today.",
                    "Choose EC2: steady high load where reserved pricing wins, GPU tasks, special kernel/daemon needs.",
                    "Fargate Spot: ~70% off for interruptible tasks - workers, batch.",
                    "Same task definitions either way - the launch type is a service-level choice, mixable in one cluster.",
                ],
                "example": "aws ecs create-service ...\n  --launch-type FARGATE \\\n  --network-configuration \\\n   \"awsvpcConfiguration={subnets=[private],\n    securityGroups=[app-sg]}\"",
                "answer": "Fargate is serverless containers - per-task CPU/memory, no hosts to patch, billed per second; EC2 launch type hands us the instances with their ops burden but cheaper economics at steady high utilization, plus GPU and daemon options. My default is Fargate with Fargate Spot for workers, switching to EC2 only when sustained scale or special hardware justifies it.",
            },
            {
                "title": "A2.5  App Runner",
                "what": "App Runner is the simplest AWS container deploy: point it at an ECR image or repo, it handles load balancing, HTTPS, autoscaling - PaaS-style.",
                "points": [
                    "Give it an image (or source repo with a buildfile) -> it builds/pulls, runs N copies, terminates TLS, autoscales on concurrent requests - no ALB, no cluster, no task definitions to manage.",
                    "Per-service config is tiny: CPU/memory, min/max instances, env vars, health check path, auto-deploy on new image push.",
                    "Scales down to near-idle cost (provisioned-but-paused instances) - great for low/spiky traffic APIs and demos.",
                    "Limits vs ECS: less network control (VPC connector needed for RDS access), request/response model only (no long websockets historically, no workers/daemons), fewer knobs overall.",
                    "The ladder to name: App Runner (simplest) -> ECS Fargate (production control) -> EKS (k8s ecosystem) - choose the lowest rung that fits.",
                    "My production use: the RAG chatbot ran on App Runner - Flask container from ECR, HTTPS and autoscaling out of the box (resume story).",
                ],
                "example": "aws apprunner create-service \\\n  --service-name rag-chatbot \\\n  --source-configuration '{\n    \"ImageRepository\": {\n      \"ImageIdentifier\":\n        \"...ecr.../rag-bot:latest\",\n      \"ImageRepositoryType\": \"ECR\"}}'",
                "answer": "App Runner is AWS's PaaS for containers: point it at an ECR image and it gives HTTPS, load balancing and request-based autoscaling with near-zero configuration - I ran my production RAG chatbot on it. The trade is control: VPC access needs a connector and there are no background workers, so the ladder is App Runner for simple web services, ECS Fargate when architecture grows, EKS for the k8s world.",
            },
            {
                "title": "A2.6  ALB and Auto Scaling",
                "what": "The ALB spreads HTTP traffic across healthy targets with layer-7 routing; auto scaling adjusts how many targets exist.",
                "points": [
                    "ALB = layer 7: routes by path (/api/* -> api service), host, headers - target groups hold the targets (ECS tasks via awsvpc IPs).",
                    "Health checks per target group: fail threshold -> target pulled from rotation; ECS replaces it. This gating is what makes rolling deploys zero-downtime.",
                    "TLS terminates at the ALB with an ACM certificate (free, auto-renewing); HTTP->HTTPS redirect rule is standard.",
                    "ALB vs NLB: layer 7 features vs layer 4 raw TCP performance/static IPs - the standard comparison question.",
                    "Auto scaling: target tracking (keep CPU at 60%, or requests-per-target at N) is the sane default; step scaling for custom logic; scheduled for known peaks.",
                    "Scale on the right metric: request count per target often beats CPU for I/O-bound APIs.",
                    "Sticky sessions exist but stateless apps + external sessions (Redis) scale cleaner.",
                ],
                "example": "listener 443 (ACM cert)\n  /api/*  -> tg-api  (ECS service A)\n  /*      -> tg-web  (ECS service B)\nauto scaling: target-tracking\n  ALBRequestCountPerTarget = 200",
                "answer": "The ALB routes at layer 7 - path and host rules to target groups - terminating TLS with ACM certs, and its health checks gate which tasks receive traffic, enabling zero-downtime rolls. NLB is the layer-4 alternative for raw TCP or static IPs. Scaling uses target tracking - requests-per-target suits I/O-bound APIs better than CPU - and the service adds or removes tasks to hold that target.",
            },
            {
                "title": "A2.7  Lambda - Serverless Functions",
                "what": "Lambda runs code per event with zero servers - billed per millisecond, scaling automatically - ideal for glue, events and spiky workloads.",
                "points": [
                    "Deploy a function (zip or container image up to 10GB); triggers: API Gateway HTTP, S3 events, SQS messages, EventBridge schedules, DynamoDB streams.",
                    "Scale = concurrency: each concurrent event gets an execution environment - thousands in parallel with no config.",
                    "Limits that decide fit: 15-minute max runtime, memory 128MB-10GB (CPU scales with memory), ephemeral /tmp, stateless between invocations.",
                    "Cold start: first invocation in a fresh environment adds latency (Python ~100-400ms) - mitigations: provisioned concurrency, lighter deps, keep-warm pings.",
                    "Right fit: event glue (S3 upload -> thumbnail), scheduled jobs, SQS consumers, spiky/low-traffic APIs. Wrong fit: long-running, steady high-throughput services (a container is cheaper), websockets.",
                    "Lambda + SQS pairing: queue buffers, Lambda consumes with retries and DLQ - the standard async pattern.",
                    "Versus containers: Lambda for event-driven bursts, ECS for always-on services - cost math flips with sustained load.",
                ],
                "example": "def handler(event, context):\n    for rec in event[\"Records\"]:      # SQS batch\n        order = json.loads(rec[\"body\"])\n        process(order)\n# trigger: SQS queue, batch size 10,\n# DLQ after 3 failed receives",
                "answer": "Lambda runs functions per event - S3 uploads, SQS messages, schedules, API Gateway - scaling by concurrency and billed per millisecond. The fit boundaries: 15-minute cap, stateless, cold starts mitigable with provisioned concurrency. I use it for event glue and queue consumers with DLQs, and keep always-on APIs in containers where sustained-load economics win.",
            },
        ],
    },
    {
        "phase": "AWS Phase 3 - Data and Messaging",
        "topics": [
            {
                "title": "A3.1  RDS - Managed Relational Databases",
                "what": "RDS runs Postgres/MySQL managed - backups, patching, failover handled - with Multi-AZ for availability and read replicas for scale.",
                "points": [
                    "Managed = AWS does provisioning, OS/DB patching, automated backups with point-in-time restore, snapshots - no SSH into the DB host.",
                    "Multi-AZ: a synchronous standby in another AZ; failure -> automatic failover (DNS flips, ~1-2 min). It is for AVAILABILITY - the standby serves no reads.",
                    "Read replicas: async copies that DO serve reads - offload reports/dashboards; app routes read-only queries there (replication lag = eventual consistency, know it).",
                    "Multi-AZ vs read replica is THE classic question: availability vs read scaling - production uses both.",
                    "Connections: apps connect via endpoint DNS; SG allows 5432 only from app SG; credentials from Secrets Manager; RDS Proxy pools connections for Lambda/many-task setups.",
                    "Aurora: AWS's re-engineered engine - shared storage across 6 copies, faster failover, serverless v2 autoscaling - name it as the step up.",
                    "Storage autoscaling, Performance Insights for slow-query hunting.",
                ],
                "example": "DATABASE_URL = (\n \"postgresql://app:\" + secret +\n \"@mailflow.abc123.ap-south-1\"\n \".rds.amazonaws.com:5432/mailflow\")\n# SG: 5432 from app-sg only\n# reads -> replica endpoint",
                "answer": "RDS is managed Postgres/MySQL - automated backups, patching and point-in-time restore. Multi-AZ keeps a synchronous standby for automatic failover (availability, no reads); read replicas are async and serve read traffic with some lag (scaling) - production uses both. Access flows through SG chains and Secrets Manager, RDS Proxy pools connections, and Aurora is the higher-end engine to name.",
            },
            {
                "title": "A3.2  ElastiCache - Redis on AWS",
                "what": "ElastiCache is managed Redis (or Memcached) - the shared in-memory layer for caching, sessions, rate limiting and queues.",
                "points": [
                    "Managed Redis: patching, failover, replication handled; app code is unchanged - same redis client, an AWS endpoint.",
                    "Use cases from my stack: Django/FastAPI cache backend, session store, DRF throttle counters, Celery broker, hot API response caching.",
                    "Cluster mode off = primary + replicas (failover HA); cluster mode on = sharded across nodes for write scale.",
                    "Cache patterns: cache-aside (app checks cache, misses to DB, fills cache) is the default; TTLs on everything; invalidation on writes - same discipline as the Django caching notes.",
                    "Eviction policy when memory fills: allkeys-lru typical for pure cache; noeviction for queues (writes fail loudly instead of silently dropping jobs).",
                    "In-VPC only, SG-controlled - not internet-exposed; encryption + AUTH token for compliance.",
                    "Valkey (Redis fork) engine option post-license-change - naming it shows currency.",
                ],
                "example": "CACHES = {\"default\": {\n  \"BACKEND\": \"django_redis.cache.RedisCache\",\n  \"LOCATION\":\n   \"rediss://mailflow-cache.abc.cache\"\n   \".amazonaws.com:6379/1\"}}\n# same client, managed endpoint",
                "answer": "ElastiCache is managed Redis - the shared memory layer my apps already use for caching, sessions, throttling and Celery brokering, just with an AWS endpoint and no node ops. Replication gives failover, cluster mode shards for scale, cache-aside with TTLs is the working pattern, and eviction policy matters: LRU for caches but noeviction where Redis backs a queue.",
            },
            {
                "title": "A3.3  DynamoDB - When NoSQL (short)",
                "what": "DynamoDB is AWS's serverless key-value store - single-digit-millisecond lookups at any scale, in exchange for query-pattern-first design.",
                "points": [
                    "Serverless: no instances, pay per request (on-demand) or provisioned capacity; scales automatically.",
                    "Model: partition key (+ optional sort key) -> item. Blazing for get-by-key and key-range queries; no joins, no ad-hoc SQL.",
                    "Design is access-pattern-first: know the queries, shape the keys; GSIs (secondary indexes) add alternate lookups at extra cost.",
                    "Fits: sessions, carts, user profiles, IoT/event firehoses, feature flags - simple lookups at brutal scale.",
                    "Does not fit: relational data, flexible reporting, aggregations - that stays in RDS; scan operations are the anti-pattern tax.",
                    "Extras worth naming: TTL auto-expiry, streams (change events -> Lambda), global tables (multi-region).",
                    "Honest 3-YOE answer: default to Postgres; reach for DynamoDB when a known key-value pattern must scale beyond comfortable RDS territory.",
                ],
                "example": "table.get_item(Key={\n  \"pk\": f\"USER#{uid}\",\n  \"sk\": \"CART\"})\n# ms lookup at any scale;\n# but no JOIN, no ad-hoc SQL",
                "answer": "DynamoDB is serverless key-value storage with constant-millisecond lookups at any scale - but it demands access-pattern-first design: partition/sort keys shaped to the queries, GSIs for alternates, no joins or ad-hoc analytics. I keep relational and reporting data in RDS and use DynamoDB for high-scale simple lookups like sessions and event streams.",
            },
            {
                "title": "A3.4  SQS and SNS - Queues and Pub/Sub",
                "what": "SQS is a message queue - one consumer group works off each message; SNS is pub/sub - one event fans out to many subscribers.",
                "points": [
                    "SQS: producers enqueue, consumers poll, process, delete. Visibility timeout hides an in-flight message; crash = message reappears - at-least-once delivery, so consumers must be IDEMPOTENT (the key word).",
                    "DLQ: after N failed receives the message moves to a dead-letter queue for inspection - no infinite retry loops.",
                    "Standard queue = massive throughput, occasional duplicates, loose order; FIFO = strict order + exactly-once-ish within a message group, lower throughput.",
                    "SNS: topics with many subscribers - SQS queues, Lambda, email, webhooks. Fan-out pattern: SNS topic -> multiple SQS queues = one event, many independent consumers.",
                    "SQS decouples and buffers (order placed -> queue absorbs spikes -> workers process at their pace); SNS broadcasts (order-events topic -> invoice queue + analytics queue + notification Lambda).",
                    "Versus Celery: same queue concepts - SQS can BE the Celery broker; EventBridge is the richer event-bus alternative to name.",
                    "Long polling reduces empty-receive cost; batch operations cut API calls.",
                ],
                "example": "# consumer loop (idempotent!)\nmsgs = sqs.receive_message(\n  QueueUrl=Q, WaitTimeSeconds=20,\n  MaxNumberOfMessages=10)\nfor m in msgs.get(\"Messages\", []):\n    if not already_done(m):  # dedupe\n        process(m)\n    sqs.delete_message(QueueUrl=Q,\n      ReceiptHandle=m[\"ReceiptHandle\"])",
                "answer": "SQS queues decouple producers from consumers with at-least-once delivery - visibility timeouts, DLQs after repeated failures, and idempotent consumers as the non-negotiable discipline; FIFO adds ordering at throughput cost. SNS broadcasts one event to many subscribers, and SNS-to-multiple-SQS fan-out is the standard event pattern. Same concepts as Celery - SQS can even be its broker.",
            },
            {
                "title": "A3.5  Route 53 and CloudFront - DNS and CDN",
                "what": "Route 53 is AWS DNS - domains resolving to your infrastructure with routing policies; CloudFront is the CDN caching content at edge locations worldwide.",
                "points": [
                    "Route 53: hosted zone per domain; records point names at resources - alias records map the apex domain straight to ALB/CloudFront (a thing plain CNAME cannot do).",
                    "Routing policies: simple, weighted (canary %), latency-based, failover (health-checked primary -> standby), geolocation - each is an interview one-liner.",
                    "CloudFront: 400+ edge locations cache content near users - static assets from an S3 origin, dynamic API acceleration over AWS's backbone; origin access control locks the bucket to CloudFront only.",
                    "Cache behaviors per path pattern (/static/* long TTL, /api/* no-cache but still TLS/HTTP3 benefits); invalidations or hashed filenames handle deploys.",
                    "Free TLS via ACM on both; CloudFront + WAF adds edge protection (rate rules, common attacks).",
                    "The standard front door: Route 53 -> CloudFront -> S3 (static) + ALB (API) - the architecture-diagram answer.",
                    "S3 static site + CloudFront is how a React build ships globally for pennies.",
                ],
                "example": "app.example.com  A(alias) -> CloudFront\n  /static/* -> S3 origin (long TTL)\n  /api/*    -> ALB origin (no cache)\ncert: ACM us-east-1 (CloudFront)",
                "answer": "Route 53 hosts DNS with alias records mapping even apex domains to AWS resources, plus weighted, latency and failover routing policies. CloudFront caches at edge locations - S3 origins for static content with locked-down bucket access, ALB origins for APIs - with ACM TLS and WAF at the edge. The standard front door is Route 53 into CloudFront splitting /static to S3 and /api to the ALB.",
            },
        ],
    },
]
