"""Content for Django_Interview_Theory.docx.

Level: 3-year-experience answers - not beginner definitions. Each topic still
uses simple English, but the content goes to the depth an interviewer expects
from someone with production Django behind them. Small example per topic.
Add one phase at a time, then run:  python build_docx.py django
"""

DOC_TITLE = "Django Interview Theory Notes"
DOC_SUBTITLE = "3-year-experience depth  |  Simple English + examples  |  Sanket Kolhe"

CONTENT = [
    {
        "phase": "Django Phase 1 - Core Architecture",
        "topics": [
            {
                "title": "D1.1  What is Django - MTV and Batteries Included",
                "what": "Django is a high-level Python web framework that ships with everything a serious app needs: ORM, auth, admin, migrations, security.",
                "points": [
                    "\"Batteries included\": ORM, migrations, authentication, admin panel, forms, caching, security middleware - all built in. Flask/FastAPI leave these to libraries we assemble ourselves.",
                    "MTV = Model, Template, View. Same idea as MVC with renamed parts: Model = data (MVC model), View = business logic (MVC controller), Template = presentation (MVC view). Django's URL dispatcher plays the router.",
                    "Design philosophy: DRY (define a model once - migrations, admin, forms all derive from it) and convention over configuration.",
                    "Built for fast, safe development: the admin alone replaces weeks of internal-tool work.",
                    "Where it fits: content sites, dashboards, standard CRUD/REST backends. Where it fights us: highly async workloads, tiny microservices - there FastAPI is leaner.",
                    "Scales fine in practice (Instagram, YouTube-scale usage) - the bottleneck is almost always the database, not the framework.",
                ],
                "example": "django-admin startproject shop\npython manage.py startapp orders\npython manage.py runserver",
                "answer": "Django is a batteries-included Python framework following MTV - model for data, view for logic, template for presentation, with the URL dispatcher routing. Its DRY design means one model definition drives migrations, admin and forms. I pick Django for full-featured backends and admin-heavy products, and FastAPI when I need lean async APIs.",
            },
            {
                "title": "D1.2  Request/Response Cycle",
                "what": "Every request flows: web server -> WSGI/ASGI -> middleware (down) -> URL resolver -> view -> middleware (up) -> response.",
                "points": [
                    "Production entry: nginx receives the request and proxies to gunicorn/uwsgi, which speaks WSGI to Django (or uvicorn speaking ASGI for async).",
                    "Django builds an HttpRequest object, then runs the request through the MIDDLEWARE list top-down (security, sessions, auth attach request.user here).",
                    "The URL resolver matches the path against urlpatterns and picks a view, passing captured parameters.",
                    "The view runs business logic - ORM queries, serialization - and returns an HttpResponse (or raises, and exception middleware turns it into an error response).",
                    "The response passes back up the middleware stack bottom-up (so a middleware can time or modify both sides), then goes out through WSGI to the client.",
                    "Knowing this order explains real bugs: request.user missing means auth middleware order is wrong; CORS headers missing means that middleware is too low.",
                ],
                "example": "Browser -> nginx -> gunicorn (WSGI)\n -> SecurityMiddleware -> SessionMiddleware\n -> AuthenticationMiddleware -> URL resolver\n -> view -> ORM -> HttpResponse\n -> back up middleware -> client",
                "answer": "nginx hands the request to gunicorn, which calls Django through WSGI. Django runs middleware top-down - sessions and auth attach request.user - resolves the URL to a view, the view does the work and returns a response, which travels back up the middleware stack. Middleware order matters: auth issues and missing headers usually trace back to it.",
            },
            {
                "title": "D1.3  Project vs App and Settings",
                "what": "A project is the whole site (settings + root urls); an app is one self-contained feature module - a project holds many apps.",
                "points": [
                    "Project folder: settings.py, root urls.py, wsgi.py/asgi.py. App folder: models.py, views.py, urls.py, admin.py, tests.py, migrations/.",
                    "Apps keep code modular and reusable: an 'orders' app, a 'payments' app - each owns its models and URLs. INSTALLED_APPS registers them.",
                    "Real-world settings are split per environment: base.py + dev.py + prod.py, or one settings.py driven by environment variables.",
                    "Secrets (SECRET_KEY, DB password, API keys) never live in code - environment variables or a .env via django-environ.",
                    "DEBUG=True must never reach production: it leaks stack traces and settings on every error page.",
                    "Key settings to know: DATABASES, ALLOWED_HOSTS, MIDDLEWARE, TEMPLATES, STATIC_/MEDIA_ROOT, CACHES.",
                ],
                "example": "shop/            # project\n  settings/base.py, dev.py, prod.py\n  urls.py\norders/          # app\n  models.py views.py urls.py admin.py\nSECRET_KEY = os.environ[\"SECRET_KEY\"]",
                "answer": "The project is the site-level configuration; apps are pluggable feature modules with their own models, views and URLs, registered in INSTALLED_APPS. In production I split settings per environment, feed secrets from environment variables, and never ship DEBUG=True - it leaks stack traces and config.",
            },
            {
                "title": "D1.4  URL Routing",
                "what": "urlpatterns map URL paths to views; include() nests each app's URLs, and names make URLs reversible.",
                "points": [
                    "path(\"orders/<int:pk>/\", views.order_detail, name=\"order-detail\") - the converter (<int:pk>) validates and casts, passing pk into the view.",
                    "Converters: int, str, slug, uuid, path. re_path() takes a regex when converters are not enough.",
                    "Root urls.py include()s app urls: path(\"api/orders/\", include(\"orders.urls\")) - apps stay self-contained.",
                    "Never hardcode URLs: reverse(\"order-detail\", args=[5]) in Python, {% url %} in templates - renaming paths then breaks nothing.",
                    "app_name = \"orders\" adds a namespace: reverse(\"orders:order-detail\") - avoids name clashes between apps.",
                    "Order matters: first match wins, top to bottom.",
                ],
                "example": "# orders/urls.py\napp_name = \"orders\"\nurlpatterns = [\n  path(\"<int:pk>/\", views.detail, name=\"detail\"),\n]\n# usage\nreverse(\"orders:detail\", args=[5])  # /api/orders/5/",
                "answer": "urlpatterns map paths to views with typed converters like <int:pk>, apps keep their own urls.py pulled in with include(), and named routes plus namespaces let me build URLs with reverse() instead of hardcoding. Matching is top-down, first hit wins.",
            },
            {
                "title": "D1.5  FBV vs CBV",
                "what": "Function-based views are plain functions per request; class-based views organize behavior in classes with methods per HTTP verb and heavy reuse via mixins.",
                "points": [
                    "FBV: def order_list(request): explicit, readable, all logic visible in one place. if request.method == \"POST\" branches by hand.",
                    "CBV: class OrderList(View) with get()/post() methods - the verb dispatch is automatic.",
                    "Generic CBVs (ListView, DetailView, CreateView) implement whole CRUD patterns in a few lines - queryset + template and done.",
                    "CBV power = mixins (LoginRequiredMixin etc.) and overridable hooks (get_queryset, get_context_data).",
                    "CBV cost: logic spreads across parent classes - debugging means knowing the method resolution order; over-customized CBVs get harder to follow than an explicit FBV.",
                    "Working rule: generic CRUD -> CBV; unusual or branching logic -> FBV. In DRF the same idea appears as APIView vs generics vs ViewSets.",
                ],
                "example": "class OrderList(ListView):\n    model = Order\n    paginate_by = 20\n    def get_queryset(self):\n        return Order.objects.filter(\n            user=self.request.user)",
                "answer": "FBVs are explicit functions - best when logic is custom; CBVs dispatch by HTTP method and shine with generic views and mixins for standard CRUD, at the cost of logic hidden in the class hierarchy. I use generics for plain CRUD and drop to FBVs for complex flows - same trade-off as DRF's ViewSets vs APIView.",
            },
            {
                "title": "D1.6  Templates (short)",
                "what": "Django's template language renders HTML with variables, tags and filters, kept deliberately logic-light.",
                "points": [
                    "{{ variable }} outputs a value, {% tag %} runs logic (for, if, block), {{ value|filter }} transforms (date, upper, default).",
                    "Template inheritance: base.html defines {% block %}s; child templates extend and fill them - one layout, many pages.",
                    "Auto-escaping is ON: variables are HTML-escaped by default, which blocks XSS. |safe disables it - only for trusted content.",
                    "Business logic stays in views/models; templates only display. No arbitrary Python in templates - by design.",
                    "{% csrf_token %} inside forms pairs with CSRF middleware.",
                    "As an API developer: DRF responses skip templates entirely - but the admin, emails and error pages still use them.",
                ],
                "example": "{% extends \"base.html\" %}\n{% block content %}\n  {% for o in orders %}\n    <p>{{ o.id }} - {{ o.amount|floatformat:2 }}</p>\n  {% endfor %}\n{% endblock %}",
                "answer": "Django templates render display-only HTML with variables, tags and filters, plus inheritance through blocks for shared layouts. Auto-escaping is on by default, which prevents XSS unless someone marks content |safe. In API work I rarely touch them, but admin and transactional emails still run on templates.",
            },
        ],
    },
    {
        "phase": "Django Phase 2 - Models and ORM",
        "topics": [
            {
                "title": "D2.1  Models and Migrations",
                "what": "A model is a Python class mapped to one database table; migrations are versioned files that evolve the schema to match the models.",
                "points": [
                    "Each attribute is a field (CharField, DecimalField, ForeignKey...) mapping to a column; Django adds an auto id primary key unless we define one.",
                    "Flow: edit models -> makemigrations (writes a migration file from the diff) -> migrate (applies pending ones, recorded in the django_migrations table).",
                    "Migrations are code: committed to git, reviewed, run identically on every environment - that is the whole point.",
                    "sqlmigrate shows the SQL a migration will run; --fake marks one applied without running (for syncing weird states).",
                    "Data migrations (RunPython) transform existing rows during schema changes - e.g. filling a new column.",
                    "Production care: adding NOT NULL without default needs a two-step migration; huge-table ALTERs can lock - plan them.",
                    "Meta options worth knowing: db_table, ordering, indexes, constraints, unique_together.",
                ],
                "example": "class Order(models.Model):\n    customer = models.ForeignKey(\"Customer\",\n        on_delete=models.CASCADE)\n    amount = models.DecimalField(max_digits=10,\n        decimal_places=2)\n    class Meta:\n        indexes = [models.Index(fields=[\"customer\"])]\n# python manage.py makemigrations && migrate",
                "answer": "Models map classes to tables; makemigrations diffs the models into versioned migration files and migrate applies them, tracked in django_migrations. They live in git so every environment evolves identically. At 3 years I also know data migrations with RunPython, sqlmigrate to preview SQL, and that NOT NULL additions and big-table ALTERs need care in production.",
            },
            {
                "title": "D2.2  QuerySet - Lazy Evaluation and Caching",
                "what": "A QuerySet is a lazy description of a query - no SQL runs until the data is actually needed, and results are then cached on that QuerySet.",
                "points": [
                    "qs = Order.objects.filter(status=\"paid\") runs NOTHING. Chaining more filters still runs nothing - each returns a new QuerySet.",
                    "Evaluation triggers: iterating (for), list(), len(), bool()/if, slicing with a step, repr, serialization.",
                    "After first evaluation the results cache inside the QuerySet - looping it twice hits the DB once.",
                    "Trap: two separate expressions (qs.count() then list(qs)... or building qs twice) are separate queries - assign once and reuse.",
                    "exists() and count() are cheaper than len(list(qs)) when we only need a check or a number.",
                    "values()/values_list() fetch dicts/tuples instead of model objects - lighter for reports; only() and defer() control columns.",
                    "iterator() streams rows without caching - for processing millions of rows without eating RAM.",
                ],
                "example": "qs = Order.objects.filter(status=\"paid\")  # no SQL yet\nif qs.exists():          # cheap EXISTS query\n    total = qs.count()   # COUNT query\n    for o in qs:         # SELECT + cache\n        ...\n    for o in qs:         # cached - no new query",
                "answer": "QuerySets are lazy - filters just build the query, and SQL runs only on iteration, list(), len() or bool(), after which results cache on that object. I use exists() and count() for cheap checks, values_list() for light reads, iterator() for huge datasets, and I reuse one evaluated queryset instead of re-evaluating.",
            },
            {
                "title": "D2.3  select_related vs prefetch_related - The N+1 Problem",
                "what": "N+1 means one query for the list plus one more per row for its relation; select_related and prefetch_related collapse that into 1-2 queries.",
                "points": [
                    "The bug: for o in Order.objects.all(): print(o.customer.name) - 1 query for orders + 1 per order for its customer. 200 orders = 201 queries.",
                    "select_related(\"customer\"): SQL JOIN, one query. For single-valued relations - ForeignKey and OneToOne.",
                    "prefetch_related(\"items\"): two queries (parents, then all children WHERE parent_id IN (...)), joined in Python. For multi-valued - ManyToMany and reverse FK.",
                    "Both chain and mix: Order.objects.select_related(\"customer\").prefetch_related(\"items\").",
                    "Prefetch(queryset=...) customizes the prefetch - filter or select_related inside it.",
                    "Follow relations with __: select_related(\"customer__city\").",
                    "This is THE classic Django performance interview question - name the symptom (page slow, query count huge) and the fix.",
                ],
                "example": "# 201 queries:\nfor o in Order.objects.all():\n    print(o.customer.name)\n# 1 query:\nfor o in Order.objects.select_related(\"customer\"):\n    print(o.customer.name)\n# M2M: 2 queries\nOrder.objects.prefetch_related(\"items\")",
                "answer": "N+1 is one list query plus a query per row for its relation. select_related fixes single-valued relations (FK, OneToOne) with a JOIN in one query; prefetch_related fixes multi-valued ones (M2M, reverse FK) with a second IN-query stitched in Python. I spot it via query counts in debug toolbar and fix it at the queryset.",
            },
            {
                "title": "D2.4  F Objects, Q Objects and Aggregation",
                "what": "F references a column inside the query, Q builds OR/NOT conditions, and aggregate/annotate compute values in the database.",
                "points": [
                    "F avoids race conditions: Product.objects.filter(id=5).update(stock=F(\"stock\") - 1) - the DB does the maths atomically; read-modify-save in Python loses concurrent updates.",
                    "F also compares columns to each other: filter(sold=F(\"stock\")).",
                    "Q enables OR and NOT, which plain filter kwargs (always AND) cannot: filter(Q(status=\"new\") | Q(priority=\"high\")), and ~Q for negation.",
                    "aggregate() collapses the whole queryset to one dict: aggregate(total=Sum(\"amount\")).",
                    "annotate() adds a computed value PER ROW/group: Customer.objects.annotate(order_count=Count(\"order\")) - then filter or order by it.",
                    "annotate + values gives GROUP BY reports; functions: Count, Sum, Avg, Min, Max, plus Case/When for conditional aggregates.",
                    "All of this runs in the database - almost always faster than looping in Python.",
                ],
                "example": "Product.objects.filter(pk=5).update(\n    stock=F(\"stock\") - 1)          # atomic\nOrder.objects.filter(\n    Q(status=\"new\") | Q(amount__gt=5000))\nCustomer.objects.annotate(\n    n=Count(\"order\")).filter(n__gt=10)",
                "answer": "F pushes column references into SQL - update(stock=F('stock')-1) is atomic and race-free, unlike read-modify-save. Q composes OR/NOT conditions that keyword filters can't. aggregate gives one summary row, annotate computes per row or group for filtering and ordering - all executed in the database where it belongs.",
            },
            {
                "title": "D2.5  Relationships - FK, OneToOne, ManyToMany",
                "what": "ForeignKey is many-to-one, OneToOneField is one-to-one, ManyToManyField creates a junction table - with related_name controlling the reverse side.",
                "points": [
                    "ForeignKey(Customer, on_delete=...): many orders per customer. on_delete is mandatory: CASCADE (delete children), PROTECT (block), SET_NULL (needs null=True).",
                    "PROTECT is the safe default for business data - accidental parent deletes fail loudly instead of silently wiping children.",
                    "OneToOneField: profile-per-user pattern; access both ways as single objects.",
                    "ManyToManyField: Django creates the join table; through=\"Membership\" replaces it with our own model when the relation itself has fields (date joined, role).",
                    "Reverse access: customer.order_set by default; related_name=\"orders\" renames it (customer.orders.all()).",
                    "related_name=\"+\" disables the reverse when it is never needed.",
                    "Self-relations: ForeignKey(\"self\") builds trees (category parent); M2M to self builds graphs (followers, symmetrical=False).",
                ],
                "example": "class Order(models.Model):\n    customer = models.ForeignKey(Customer,\n        on_delete=models.PROTECT,\n        related_name=\"orders\")\n    tags = models.ManyToManyField(Tag, blank=True)\n# customer.orders.all(), tag.order_set.all()",
                "answer": "FK models many-to-one with a mandatory on_delete - I default to PROTECT for business data; OneToOne is the profile pattern; M2M builds a junction table, replaced by a through model when the relation carries its own fields. related_name names the reverse accessor, and self-referencing FKs model hierarchies.",
            },
            {
                "title": "D2.6  Model Inheritance - Abstract, Multi-table, Proxy",
                "what": "Django offers three inheritance styles: abstract (shared fields, no extra table), multi-table (each class a table), proxy (same table, new behavior).",
                "points": [
                    "Abstract base (Meta: abstract = True): children copy its fields into their own tables; the base has no table. The workhorse - TimeStampedModel with created/updated used everywhere.",
                    "Multi-table: both parent and child get tables joined by an implicit OneToOne. Every child query joins - a hidden performance cost people forget. Rarely the right choice.",
                    "Proxy (Meta: proxy = True): no new table, no new fields - just different Python behavior: custom manager, different ordering, extra methods on the same data.",
                    "Choosing: share common fields -> abstract; genuinely need parent-level querying across subtypes -> multi-table (or reconsider: one table + type field); same data, different behavior -> proxy.",
                    "Interviewers probe multi-table because of the surprise JOINs and the parent_ptr link.",
                ],
                "example": "class TimeStamped(models.Model):\n    created = models.DateTimeField(auto_now_add=True)\n    updated = models.DateTimeField(auto_now=True)\n    class Meta:\n        abstract = True\nclass Order(TimeStamped): ...  # own table only",
                "answer": "Abstract bases copy shared fields into each child's table - my default for things like timestamps. Multi-table inheritance gives every class a table linked by OneToOne, silently JOINing on each child query, so I avoid it unless cross-type querying truly pays. Proxy models reuse the same table with different behavior - managers, ordering, methods.",
            },
            {
                "title": "D2.7  Transactions - atomic and select_for_update",
                "what": "transaction.atomic wraps DB work in all-or-nothing blocks, and select_for_update row-locks data against concurrent edits.",
                "points": [
                    "Default Django mode is autocommit - every ORM write commits alone. Multi-step operations need explicit grouping.",
                    "with transaction.atomic(): everything inside commits together or rolls back on exception. Also usable as a decorator.",
                    "atomic blocks nest - inner blocks become savepoints, so an inner failure can roll back partially.",
                    "ATOMIC_REQUESTS=True wraps every request in a transaction - simple, but holds transactions longer under load.",
                    "select_for_update() adds FOR UPDATE - other transactions wait for the lock: the fix for stock/wallet race conditions. Must run inside atomic.",
                    "F() expressions are the lighter alternative for simple counters; select_for_update is for read-then-decide logic.",
                    "on_commit(callback) delays side effects (emails, Celery tasks) until after commit - so a rollback cannot leave a task pointing at data that never got saved.",
                ],
                "example": "with transaction.atomic():\n    p = (Product.objects\n         .select_for_update().get(pk=5))\n    if p.stock > 0:\n        p.stock -= 1\n        p.save()\ntransaction.on_commit(lambda:\n    notify_task.delay(p.id))",
                "answer": "transaction.atomic makes a block all-or-nothing with savepoints when nested; select_for_update inside it row-locks against races - my pattern for stock and payment flows, with F() expressions for simple atomic counters. on_commit defers emails and Celery tasks until the data is truly committed.",
            },
            {
                "title": "D2.8  Custom Managers and QuerySets",
                "what": "A custom QuerySet holds reusable, chainable query logic; a manager exposes it as the model's entry point (objects).",
                "points": [
                    "Problem: filter(status='active', deleted_at__isnull=True) copy-pasted through the codebase - one rule change touches twenty files.",
                    "Solution: methods on a custom QuerySet - Order.objects.paid().recent().for_customer(c) - named business language, chainable.",
                    "Wiring: OrderQuerySet.as_manager(), or a Manager whose get_queryset() returns the custom QuerySet.",
                    "Default-filtering managers (e.g. auto-hiding soft-deleted rows) are risky: admin and shell silently miss data. Keep objects honest; add a separate manager or explicit methods for filtered views.",
                    "The first declared manager is the default one used by admin and dumpdata - order matters.",
                    "This is the standard 'fat model, thin view' pattern - query logic lives at the data layer where it is testable.",
                ],
                "example": "class OrderQuerySet(models.QuerySet):\n    def paid(self):\n        return self.filter(status=\"paid\")\n    def recent(self):\n        return self.order_by(\"-created\")[:50]\nclass Order(models.Model):\n    objects = OrderQuerySet.as_manager()\n# Order.objects.paid().recent()",
                "answer": "I put reusable filters on a custom QuerySet and expose it via as_manager, so queries read like business language and stay chainable - Order.objects.paid().recent(). I avoid default managers that silently hide rows (soft-delete traps admin and shell); explicit methods are safer, and the first manager declared is the default the admin uses.",
            },
        ],
    },
    {
        "phase": "Django Phase 3 - Middleware, Auth, Signals, Caching",
        "topics": [
            {
                "title": "D3.1  Middleware",
                "what": "Middleware is a chain of hooks that every request passes through before the view and every response passes through after it.",
                "points": [
                    "Listed in settings MIDDLEWARE - request runs the list top-down, response bottom-up. Order is functional, not cosmetic.",
                    "Built-ins do real work: SecurityMiddleware (HTTPS headers), SessionMiddleware, AuthenticationMiddleware (attaches request.user), CsrfViewMiddleware.",
                    "Auth must come after sessions - it reads the session to find the user. Wrong order = broken auth.",
                    "Custom middleware: a callable taking get_response; code before the call sees the request, after it sees the response.",
                    "A middleware can short-circuit: return a response early (rate limiting, maintenance mode) and the view never runs.",
                    "Extra hooks: process_view, process_exception, process_template_response.",
                    "Use for true cross-cutting concerns (logging, tenant resolution, timing); per-endpoint logic belongs in decorators or DRF permissions instead.",
                ],
                "example": "class TimingMiddleware:\n    def __init__(self, get_response):\n        self.get_response = get_response\n    def __call__(self, request):\n        t0 = time.time()\n        response = self.get_response(request)\n        response[\"X-Time-ms\"] = str(\n            int((time.time()-t0)*1000))\n        return response",
                "answer": "Middleware wraps every request/response: the list runs top-down on the way in, bottom-up on the way out, and order matters - auth needs sessions before it. I write one as a callable around get_response for cross-cutting concerns like timing or tenant detection, and it can short-circuit requests before any view runs.",
            },
            {
                "title": "D3.2  Signals",
                "what": "Signals let code react to events elsewhere - post_save, pre_delete - decoupling the sender from the receivers.",
                "points": [
                    "Common ones: pre_save/post_save, pre_delete/post_delete, m2m_changed, request_started/finished.",
                    "Receiver: @receiver(post_save, sender=User) def make_profile(sender, instance, created, **kw) - the created flag separates insert from update.",
                    "Registered in apps.py ready() (import the signals module there) so receivers actually load.",
                    "Right uses: reacting to models our code does not own (e.g. building a profile on User creation from a third-party auth flow).",
                    "Why to be careful: invisible control flow - a save triggers hidden work; debugging \"who changed this?\" gets painful; receivers run synchronously inside the same transaction/request.",
                    "Big gotcha: bulk operations (bulk_create, queryset.update()) do NOT fire per-object signals - logic in signals silently skips bulk paths.",
                    "Team rule of thumb: prefer explicit service functions or overridden save(); keep signals for genuine decoupling.",
                ],
                "example": "@receiver(post_save, sender=User)\ndef create_profile(sender, instance,\n                   created, **kwargs):\n    if created:\n        Profile.objects.create(user=instance)",
                "answer": "Signals are event hooks - post_save, pre_delete - that decouple reactions from the code doing the save. I register receivers in apps.ready() and use the created flag. But they hide control flow, run synchronously, and bulk operations never fire them - so I prefer explicit service-layer calls and keep signals only where real decoupling is needed.",
            },
            {
                "title": "D3.3  Authentication - Sessions and Custom User Model",
                "what": "Django ships a full auth system - hashed passwords, login sessions, and a User model that projects should replace with a custom one on day one.",
                "points": [
                    "Session flow: authenticate() checks credentials, login() stores the user id in the session, the session key rides in a cookie; AuthenticationMiddleware rebuilds request.user each request.",
                    "Passwords are salted and hashed (PBKDF2 default; argon2 available) - never stored or logged raw.",
                    "AUTH_USER_MODEL = \"accounts.User\" with a custom user (AbstractUser to extend, AbstractBaseUser to rebuild e.g. email login) - deciding this AFTER migrations exist is a painful migration story, so do it first.",
                    "Reference users via settings.AUTH_USER_MODEL / get_user_model(), never a direct import of User.",
                    "authenticate() runs through AUTHENTICATION_BACKENDS - adding a backend enables email login or SSO alongside.",
                    "login_required decorator / LoginRequiredMixin guard views; for APIs this shifts to DRF authentication classes (JWT etc. - Phase 4).",
                ],
                "example": "class User(AbstractUser):\n    phone = models.CharField(max_length=15,\n                             blank=True)\n# settings.py\nAUTH_USER_MODEL = \"accounts.User\"\n# usage\nUser = get_user_model()",
                "answer": "Django auth handles hashed passwords, authenticate/login, and sessions - the middleware rebuilds request.user from the session cookie each request. The experienced move is a custom user model via AUTH_USER_MODEL before the first migration, referenced through get_user_model(), with extra authentication backends for email or SSO login.",
            },
            {
                "title": "D3.4  Permissions and Groups",
                "what": "Django auto-creates add/change/delete/view permissions per model, lets us define custom ones, and bundles them into groups as roles.",
                "points": [
                    "Every model gets four permissions (app.add_order etc.); user.has_perm(\"orders.change_order\") checks them; admin respects them automatically.",
                    "Custom permissions in Meta: (\"can_refund\", \"Can refund orders\") - business actions, not just CRUD.",
                    "Groups = named permission sets = roles: 'support', 'accounts'. Users join groups; role changes touch the group, not every user.",
                    "Views enforce with @permission_required or PermissionRequiredMixin; is_superuser passes every check by definition.",
                    "These are model-level, not object-level - \"can edit orders\", not \"can edit THIS order\". Row-level needs django-guardian or explicit queryset filtering by ownership (the common API pattern).",
                    "In DRF this maps to permission classes; DjangoModelPermissions bridges DRF to these model permissions.",
                ],
                "example": "class Order(models.Model):\n    class Meta:\n        permissions = [\n          (\"can_refund\", \"Can refund orders\")]\n# view\n@permission_required(\"orders.can_refund\")\ndef refund(request, pk): ...",
                "answer": "Django gives per-model add/change/delete/view permissions plus custom ones declared in Meta, checked via has_perm and enforced by decorators, mixins and the admin. Groups act as roles holding permission sets. It is all model-level though - object-level control needs queryset ownership filtering or django-guardian, and in DRF it becomes permission classes.",
            },
            {
                "title": "D3.5  Security Features - CSRF, XSS, SQL Injection",
                "what": "Django blocks the classic web attacks by default - the interview answer is knowing WHAT it does and where the developer can still break it.",
                "points": [
                    "CSRF: forged cross-site POSTs riding the user's cookies. CsrfViewMiddleware + {% csrf_token %} verify a token per unsafe request. APIs using token/JWT headers skip cookies - that is why pure DRF token auth does not need CSRF.",
                    "XSS: injected scripts in rendered HTML. Templates auto-escape all variables; the developer breaks it with careless |safe or mark_safe on user content.",
                    "SQL injection: the ORM parameterizes everything. The hole is raw SQL with string formatting - raw()/cursor.execute must use params=[...], never f-strings.",
                    "Clickjacking: XFrameOptionsMiddleware sends X-Frame-Options: DENY.",
                    "HTTPS hardening: SECURE_SSL_REDIRECT, HSTS settings, SESSION_COOKIE_SECURE, CSRF_COOKIE_SECURE.",
                    "Also free: password hashing, host header validation via ALLOWED_HOSTS. python manage.py check --deploy audits prod settings.",
                    "Summary line: the framework is safe by default; incidents come from developers bypassing it.",
                ],
                "example": "# safe raw SQL\nOrder.objects.raw(\n  \"SELECT * FROM orders WHERE status = %s\",\n  params=[status])\n# NEVER: f\"... WHERE status = '{status}'\"",
                "answer": "Django defends by default: CSRF tokens on unsafe methods, template auto-escaping against XSS, a fully parameterized ORM against injection, clickjacking headers, ALLOWED_HOSTS, and hashed passwords. Breaches come from bypassing it - mark_safe on user input or f-string raw SQL - and check --deploy audits the production settings.",
            },
            {
                "title": "D3.6  Caching",
                "what": "Django caches at several levels - per-site, per-view, template fragment, or manual low-level - with Redis/Memcached as the usual backend.",
                "points": [
                    "Backends via CACHES: Redis (standard in production - shared across processes), Memcached, LocMem (per-process, dev only), database/file.",
                    "Low-level API is the workhorse: cache.get(key) / cache.set(key, value, timeout) / cache.get_or_set() around expensive queries or API calls.",
                    "@cache_page(60) caches a whole view's response; template {% cache %} caches fragments; per-site middleware caches everything (blunt).",
                    "Real problem #1 - invalidation: stale data after writes. Patterns: short TTLs, explicit cache.delete(key) on save, or key versioning.",
                    "Key discipline: include the variables in the key (f\"orders:{user_id}:{page}\") or users see each other's data - a classic production bug.",
                    "cached_property caches a computed attribute for one object's lifetime - free win for repeated property access.",
                    "Sessions can also ride the cache backend for speed.",
                ],
                "example": "from django.core.cache import cache\n\ndef dashboard_stats():\n    return cache.get_or_set(\n        \"dashboard:stats\",\n        compute_expensive_stats,  # callable\n        timeout=300)\n# on write: cache.delete(\"dashboard:stats\")",
                "answer": "I mostly use the low-level API - cache.get_or_set with Redis - around expensive queries, plus cache_page for read-heavy endpoints and fragment caching in templates. The hard part is invalidation: I keep TTLs short, delete keys on writes, and always build keys from their variables so users never see each other's cached data.",
            },
        ],
    },
    {
        "phase": "Django Phase 4 - Django REST Framework (DRF)",
        "topics": [
            {
                "title": "D4.1  What is DRF and Why",
                "what": "DRF is the standard toolkit on top of Django for building REST APIs - serialization, auth, permissions, throttling and browsable docs out of the box.",
                "points": [
                    "Plain Django returns HTML or hand-built JsonResponse; DRF adds the missing API layer: serializers (validation + conversion), class-based API views, and content negotiation.",
                    "Ships with pluggable authentication (session, token, JWT via libs), permissions, throttling, pagination, filtering, versioning - each a setting away.",
                    "The browsable API renders endpoints as web pages - exploring and testing without Postman; schema generation feeds Swagger/OpenAPI docs.",
                    "Request/Response wrappers: request.data unifies JSON/form parsing; Response picks the output format per client.",
                    "Core flow of every DRF endpoint: request -> authentication -> permissions -> throttling -> view logic -> serializer -> Response.",
                    "Alternative in the ecosystem: FastAPI for greenfield async microservices - but inside a Django project, DRF is the default answer.",
                ],
                "example": "class OrderSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = Order\n        fields = [\"id\", \"amount\", \"status\"]\n\nclass OrderViewSet(viewsets.ModelViewSet):\n    queryset = Order.objects.all()\n    serializer_class = OrderSerializer",
                "answer": "DRF layers a complete REST toolkit over Django: serializers for validation and JSON conversion, API views/viewsets, plus pluggable auth, permissions, throttling, pagination and a browsable API. Every request flows authentication -> permissions -> throttle -> view -> serializer -> Response. It is the default for APIs inside a Django codebase.",
            },
            {
                "title": "D4.2  Serializers",
                "what": "A serializer converts between model instances and JSON in both directions, validating everything on the way in.",
                "points": [
                    "ModelSerializer generates fields from the model; plain Serializer is fully manual (for non-model payloads).",
                    "Read path: serializer = OrderSerializer(order) -> .data. Write path: serializer = OrderSerializer(data=request.data); is_valid(raise_exception=True); save().",
                    "Validation layers, in order: field arguments (max_length...), validate_<field> methods, then validate() for cross-field rules - errors collect into serializer.errors.",
                    "create() and update() define how validated_data becomes rows - override them for nested writes or side effects.",
                    "Nested serializers embed related data read-only by default; writable nesting requires custom create/update - say this, it is a known pain point.",
                    "SerializerMethodField computes read-only values; source= renames/reaches through relations (source=\"customer.name\").",
                    "N+1 warning: a nested serializer touching relations per row needs select_related/prefetch_related on the view's queryset.",
                ],
                "example": "class OrderSerializer(serializers.ModelSerializer):\n    customer_name = serializers.CharField(\n        source=\"customer.name\", read_only=True)\n    class Meta:\n        model = Order\n        fields = [\"id\", \"amount\", \"customer_name\"]\n    def validate_amount(self, value):\n        if value <= 0:\n            raise serializers.ValidationError(\n                \"must be positive\")\n        return value",
                "answer": "Serializers convert models to JSON and validate incoming data back into objects - field rules first, then validate_<field>, then cross-field validate(), with create/update mapping validated data to rows. I use source= and SerializerMethodField for shaped output, know writable nested serializers need custom create/update, and pair nested output with prefetching to avoid N+1.",
            },
            {
                "title": "D4.3  APIView vs Generics vs ViewSet + Routers",
                "what": "Three abstraction levels for DRF views: APIView is manual, generics give standard CRUD pieces, ViewSets bundle CRUD and let routers generate the URLs.",
                "points": [
                    "APIView: def get/post/put/delete by hand - full control, most code. For endpoints that are not CRUD-shaped (reports, webhooks, actions).",
                    "Generics (ListCreateAPIView, RetrieveUpdateDestroyAPIView): declare queryset + serializer_class, CRUD comes free; override get_queryset() for per-user filtering.",
                    "ModelViewSet: all CRUD in one class; ReadOnlyModelViewSet for list+retrieve only.",
                    "Routers map ViewSets to URLs automatically: router.register(\"orders\", OrderViewSet) - consistent /orders/ and /orders/{id}/ with no manual paths.",
                    "@action(detail=True, methods=[\"post\"]) adds custom endpoints (orders/5/refund/) inside a ViewSet - CRUD plus custom actions together.",
                    "Choosing rule: standard resource -> ViewSet + router; slight variation -> generics; anything odd -> APIView. Same trade-off as FBV vs CBV.",
                ],
                "example": "router = DefaultRouter()\nrouter.register(r\"orders\", OrderViewSet)\n\nclass OrderViewSet(viewsets.ModelViewSet):\n    ...\n    @action(detail=True, methods=[\"post\"])\n    def refund(self, request, pk=None):\n        ...",
                "answer": "APIView gives manual per-verb methods for non-CRUD endpoints; generics wire queryset + serializer into ready CRUD views; ModelViewSet bundles full CRUD and a router generates its URLs, with @action for custom endpoints like /orders/5/refund/. I default to ViewSets for resources and drop to APIView when the endpoint is not resource-shaped.",
            },
            {
                "title": "D4.4  API Authentication - Session, Token, JWT",
                "what": "DRF authentication classes identify who is calling; session, token and JWT are the three standard schemes.",
                "points": [
                    "SessionAuthentication: cookie-based, fits same-domain frontends and the browsable API; needs CSRF handling.",
                    "TokenAuthentication (DRF built-in): one permanent token per user in the DB, sent as Authorization: Token xyz. Simple, but no expiry by default and a DB hit per request.",
                    "JWT (djangorestframework-simplejwt): signed, self-contained tokens - short-lived access token + refresh token. Stateless: no DB lookup to verify, easy horizontal scaling.",
                    "JWT trade-off: hard to revoke before expiry (blacklist app exists but reintroduces state); payload is only base64-encoded, so nothing secret inside; always HTTPS.",
                    "Flow: POST credentials -> access + refresh; client sends Authorization: Bearer <access>; on 401, refresh; short access lifetime limits stolen-token damage.",
                    "Config: DEFAULT_AUTHENTICATION_CLASSES globally, authentication_classes per view. request.user lands the same way regardless of scheme.",
                    "Mobile/SPA + microservices -> JWT; internal same-domain tools -> sessions.",
                ],
                "example": "# settings\nREST_FRAMEWORK = {\n \"DEFAULT_AUTHENTICATION_CLASSES\": (\n  \"rest_framework_simplejwt.authentication\"\n  \".JWTAuthentication\",)}\n# client\nAuthorization: Bearer eyJhbGciOi...",
                "answer": "Sessions suit same-domain apps, DRF tokens are simple but permanent and hit the DB, and JWT - my default for SPAs and mobile - is stateless with short-lived access plus refresh tokens, scaling without server session state. The trade-offs to mention: JWT revocation needs a blacklist, and the payload is readable, so no secrets inside and HTTPS always.",
            },
            {
                "title": "D4.5  Permissions and Throttling",
                "what": "Permission classes decide whether the authenticated caller MAY do this; throttle classes cap how often they may call.",
                "points": [
                    "Built-ins: IsAuthenticated, AllowAny, IsAdminUser, IsAuthenticatedOrReadOnly (read for all, write for logged-in).",
                    "has_permission runs per request; has_object_permission runs per object on detail routes - the hook for ownership rules.",
                    "Custom class: IsOwner - return obj.user == request.user in has_object_permission. Standard answer for \"users edit only their own data\", together with get_queryset filtering (defense in both places).",
                    "Multiple classes AND together; SAFE_METHODS (GET/HEAD/OPTIONS) enables read-write splits.",
                    "Failure shape: 401 when unauthenticated, 403 when authenticated but not allowed.",
                    "Throttling: AnonRateThrottle / UserRateThrottle with rates like \"100/hour\" in settings; ScopedRateThrottle gives per-endpoint budgets (tight on login/OTP). Over limit -> 429.",
                    "DRF throttling uses the cache backend - it is per-process unless a shared cache (Redis) backs it; serious rate limiting also lives at nginx/gateway.",
                ],
                "example": "class IsOwner(permissions.BasePermission):\n    def has_object_permission(self, request,\n                              view, obj):\n        return obj.user == request.user\n\nclass OrderViewSet(viewsets.ModelViewSet):\n    permission_classes = [IsAuthenticated,\n                          IsOwner]\n    def get_queryset(self):\n        return Order.objects.filter(\n            user=self.request.user)",
                "answer": "Permissions gate the action: has_permission per request, has_object_permission per object - a custom IsOwner plus queryset filtering is the standard ownership pattern; 401 vs 403 separates unauthenticated from unauthorized. Throttles cap request rates per user/anon/scope returning 429, ride the cache backend so they need Redis to be global, and heavy lifting belongs at the gateway too.",
            },
            {
                "title": "D4.6  Pagination, Filtering, Searching",
                "what": "List endpoints must page, filter and search server-side - DRF provides all three as pluggable classes.",
                "points": [
                    "PageNumberPagination: ?page=2 - simple, but deep pages get slow (OFFSET cost).",
                    "LimitOffsetPagination: ?limit=20&offset=40 - client-controlled slices.",
                    "CursorPagination: opaque cursor over an ordered unique field - stable under inserts and fast at depth; the right choice for infinite scroll feeds.",
                    "Set DEFAULT_PAGINATION_CLASS + PAGE_SIZE globally; override per view. Response carries count/next/previous links.",
                    "django-filter integration: filterset_fields = [\"status\", \"city\"] -> ?status=paid&city=Surat, with FilterSet classes for ranges and custom logic.",
                    "SearchFilter: ?search=cotton across search_fields (icontains); OrderingFilter: ?ordering=-created with an allowlist via ordering_fields.",
                    "Always cap and validate what clients can request - unbounded lists and arbitrary ordering are performance holes.",
                ],
                "example": "class OrderViewSet(viewsets.ModelViewSet):\n    filter_backends = [\n        DjangoFilterBackend,\n        filters.SearchFilter,\n        filters.OrderingFilter]\n    filterset_fields = [\"status\"]\n    search_fields = [\"customer__name\"]\n    ordering_fields = [\"created\", \"amount\"]\n# /orders/?status=paid&search=ravi&ordering=-amount",
                "answer": "I page every list endpoint - page-number for simple UIs, cursor pagination for feeds since it stays fast and stable at depth - and wire django-filter, SearchFilter and OrderingFilter for ?status=, ?search=, ?ordering= queries, always with allowlisted fields and a capped page size so clients cannot turn a list endpoint into a full table scan.",
            },
            {
                "title": "D4.7  Testing DRF APIs",
                "what": "DRF tests use APIClient/APITestCase to call endpoints like a client and assert on status codes and payloads.",
                "points": [
                    "APITestCase wraps each test in a transaction rolled back at the end - tests stay isolated.",
                    "client.get/post/put/delete with format=\"json\"; assert response.status_code and response.data.",
                    "Auth in tests: client.force_authenticate(user=user) skips the login dance and tests the endpoint itself.",
                    "The permission matrix is the real value: anonymous -> 401, wrong user -> 403/404, owner -> 200. Most API security bugs die here.",
                    "Factories (factory_boy) beat fixtures for test data - readable and maintainable.",
                    "Serializers can be unit-tested directly: feed data, assert is_valid and errors.",
                    "assertNumQueries pins the query count - the automated N+1 alarm for list endpoints.",
                ],
                "example": "class OrderAPITest(APITestCase):\n    def test_owner_only(self):\n        self.client.force_authenticate(self.user)\n        r = self.client.get(f\"/api/orders/{self.other_users_order.id}/\")\n        self.assertEqual(r.status_code, 404)\n    def test_list_query_count(self):\n        with self.assertNumQueries(3):\n            self.client.get(\"/api/orders/\")",
                "answer": "I test through APIClient - force_authenticate, hit the endpoint, assert status and payload - always covering the permission matrix: 401 anonymous, 403/404 wrong user, 200 owner. factory_boy builds data, serializers get direct unit tests, and assertNumQueries on list endpoints catches N+1 regressions automatically.",
            },
        ],
    },
    {
        "phase": "Django Phase 5 - Production and Interview Favourites",
        "topics": [
            {
                "title": "D5.1  Django vs Flask vs FastAPI",
                "what": "Django is the full-featured monolith framework, Flask the minimal classic, FastAPI the modern async-first micro-framework - the answer is trade-offs, not a winner.",
                "points": [
                    "Django: ORM, admin, auth, migrations built in - fastest to a serious product; opinionated structure keeps teams consistent. Sync-first (async support growing).",
                    "Flask: tiny core, everything chosen by us (SQLAlchemy, marshmallow...) - total freedom, more assembly and more decisions to maintain.",
                    "FastAPI: async-first on Starlette + Pydantic - type-hint-driven validation, auto OpenAPI docs, top raw throughput for I/O-heavy APIs. No ORM/admin/migrations of its own.",
                    "Performance nuance worth saying: the DB is usually the bottleneck, framework speed differences matter mostly on high-concurrency I/O.",
                    "Choose Django for products needing admin/auth/ORM as one unit; FastAPI for async microservices and ML model serving; Flask for small services or full control.",
                    "From my own work: Django/DRF for the main backends, FastAPI for lightweight AI-serving APIs (RAG endpoints, model inference).",
                ],
                "example": "Django  -> full product, admin, ORM, team scale\nFlask   -> small service, pick-your-own parts\nFastAPI -> async APIs, Pydantic, auto docs,\n           ML/AI model serving",
                "answer": "Django ships the whole product toolkit - ORM, admin, auth, migrations - ideal for full backends; Flask is a minimal core where we assemble everything; FastAPI is async-first with Pydantic validation and auto-docs, best for high-concurrency APIs and ML serving. I use Django/DRF for product backends and FastAPI for AI endpoints - and note the DB, not the framework, is usually the real bottleneck.",
            },
            {
                "title": "D5.2  Detecting N+1 and Query Debugging",
                "what": "Slow list endpoints are usually N+1 - the tools are debug toolbar, query logging, and query-count assertions in tests.",
                "points": [
                    "django-debug-toolbar (dev): per-page SQL panel - count, time, duplicates flagged. A list page with 150 similar SELECTs is the smoking gun.",
                    "connection.queries in the shell (DEBUG=True) or logging django.db.backends shows every query with timing.",
                    "assertNumQueries in tests locks the count - a regression that adds queries fails CI. The proactive tool.",
                    "silk or APM tools (Sentry performance, New Relic) find slow endpoints in production.",
                    "Fix set, in order: select_related/prefetch_related for relations; values()/only() for width; annotate for per-row computed data instead of Python loops; caching last.",
                    "Also watch: queries inside template loops and inside serializer method fields - the hidden classics.",
                ],
                "example": "# settings (dev)\nLOGGING = {\"loggers\": {\"django.db.backends\":\n  {\"level\": \"DEBUG\", \"handlers\": [\"console\"]}}}\n# test\nwith self.assertNumQueries(3):\n    self.client.get(\"/api/orders/\")",
                "answer": "I use debug toolbar's SQL panel in dev to spot duplicate query storms, log django.db.backends when needed, and pin endpoints with assertNumQueries in tests so N+1 regressions fail CI. Fixes go select_related/prefetch_related first, then column trimming with only/values, annotations instead of Python loops, and caching last. Hidden N+1s love template loops and serializer method fields.",
            },
            {
                "title": "D5.3  Static vs Media Files",
                "what": "Static files are the app's own assets (CSS, JS); media files are user uploads - different settings, storage and risk profile.",
                "points": [
                    "Static: STATIC_URL/STATIC_ROOT; collectstatic gathers all app assets into STATIC_ROOT for deployment.",
                    "Media: MEDIA_URL/MEDIA_ROOT; FileField/ImageField store the file there and keep only the path in the DB.",
                    "Django does not serve either in production - DEBUG static serving is dev-only. nginx serves them directly, or a CDN.",
                    "WhiteNoise is the middle path: Django serves static files efficiently with caching headers - standard on PaaS (Heroku-style) deploys.",
                    "Scale/multi-server answer: django-storages + S3 for media - local disk does not survive multiple app servers or redeploys.",
                    "Media is untrusted user input: validate type/size, never execute, serve from a separate domain/bucket when possible.",
                    "ManifestStaticFilesStorage adds content hashes to static names - cache-busting on deploys.",
                ],
                "example": "STATIC_ROOT = BASE_DIR / \"staticfiles\"\nMEDIA_ROOT = BASE_DIR / \"media\"\n# prod media on S3:\nDEFAULT_FILE_STORAGE = (\n  \"storages.backends.s3boto3.S3Boto3Storage\")",
                "answer": "Static files are deploy-time app assets collected by collectstatic and served by nginx, WhiteNoise or a CDN with hashed names for cache busting; media files are user uploads under MEDIA_ROOT, moved to S3 via django-storages once there is more than one server. Django itself serves neither in production, and uploads are untrusted input to validate.",
            },
            {
                "title": "D5.4  Deployment - gunicorn, nginx, WSGI/ASGI",
                "what": "The standard stack is nginx in front, gunicorn running Django workers behind it, managed by systemd or a container - ASGI/uvicorn when async matters.",
                "points": [
                    "nginx: TLS termination, serves /static and /media from disk, buffers slow clients, proxies app requests to gunicorn.",
                    "gunicorn: process manager running N WSGI workers (rule of thumb 2-4 x CPU cores); a hung worker is recycled, max-requests recycles them periodically against leaks.",
                    "WSGI = sync Python web interface (gunicorn/uwsgi); ASGI = async successor (uvicorn/daphne) - needed for async views, websockets/Channels.",
                    "runserver is a dev tool only - single-threaded, no security hardening.",
                    "Deploy checklist: DEBUG=False, ALLOWED_HOSTS set, secrets in env, migrate, collectstatic, check --deploy.",
                    "Containers: Dockerfile runs gunicorn; compose/k8s adds Postgres, Redis, Celery workers - my projects ship this way with CI/CD.",
                    "Zero-downtime basics: run migrations before switching traffic, keep migrations backward-compatible one release.",
                ],
                "example": "gunicorn shop.wsgi:application \\\n  --workers 4 --bind 127.0.0.1:8000 \\\n  --max-requests 1000\n# nginx: location /static/ { alias ...; }\n#        location / { proxy_pass http://127.0.0.1:8000; }",
                "answer": "nginx terminates TLS, serves static/media and proxies to gunicorn, which runs multiple WSGI workers sized to CPU cores; ASGI with uvicorn replaces it when async or websockets are needed. Production flips DEBUG off, loads secrets from env, runs migrate + collectstatic, and in my projects this is containerized with Docker and rolled out via CI/CD with backward-compatible migrations.",
            },
            {
                "title": "D5.5  Performance Checklist",
                "what": "Django performance work, in priority order: fix queries, trim data, cache, then offload - measured before and after.",
                "points": [
                    "1. Queries first: kill N+1 (select_related/prefetch_related), add DB indexes (db_index, Meta.indexes) matching real filters, EXPLAIN slow ones.",
                    "2. Fetch less: only()/defer()/values() for wide tables, paginate everything, count() and exists() instead of loading rows.",
                    "3. Push work to the DB: annotate/aggregate/F-updates instead of Python loops; bulk_create/bulk_update for mass writes.",
                    "4. Cache: Redis via get_or_set on hot expensive reads, cache_page on read-heavy endpoints, cached_property in objects.",
                    "5. Offload: Celery for anything slow or external (emails, PDFs, API calls) - web workers must stay fast.",
                    "6. Infra: connection pooling (CONN_MAX_AGE/pgbouncer), gunicorn worker tuning, CDN for assets.",
                    "Always measure - debug toolbar/silk/APM before and after; optimizing without numbers is guessing.",
                ],
                "example": "Order.objects.bulk_create(rows, batch_size=1000)\nProduct.objects.filter(pk=i).update(\n    views=F(\"views\") + 1)\ncache.get_or_set(\"stats\", compute, 300)",
                "answer": "My order: fix N+1 and add matching indexes, fetch less with only/values and pagination, push computation into the DB with annotate and bulk operations, cache hot reads in Redis, offload slow work to Celery, then tune pooling and workers - measuring with debug toolbar or APM before and after each step.",
            },
            {
                "title": "D5.6  Celery - Background Tasks",
                "what": "Celery runs work outside the request cycle - separate worker processes consume tasks from a broker like Redis - so slow jobs never block API responses.",
                "points": [
                    "Flow: view calls task.delay(args) -> task message goes to the broker (Redis/RabbitMQ) -> a worker process picks it up and runs it -> optional result backend stores the outcome.",
                    "Belongs in Celery: emails/SMS, report and PDF generation, third-party API calls, image processing, scheduled jobs (celery beat as cron).",
                    "Pass IDs, not objects: the row may change between enqueue and execution - refetch inside the task.",
                    "Idempotency + retries: tasks can run twice (crash after work, before ack) - design them re-runnable; autoretry_for with retry_backoff handles flaky externals.",
                    "transaction.on_commit(lambda: task.delay(id)) - otherwise the worker can start before the row is committed and hit DoesNotExist: THE classic Celery bug.",
                    "Operations: workers deploy separately from web, monitored with Flower; queues can be split (fast/slow) with dedicated workers.",
                ],
                "example": "@shared_task(autoretry_for=(RequestException,),\n             retry_backoff=True, max_retries=5)\ndef send_invoice(order_id):\n    order = Order.objects.get(pk=order_id)\n    ...\n# in view, race-safe:\ntransaction.on_commit(\n    lambda: send_invoice.delay(order.pk))",
                "answer": "Celery moves slow work - emails, reports, external APIs - to worker processes fed by a Redis/RabbitMQ broker, keeping requests fast; beat handles scheduling. The experienced details: pass IDs not objects, make tasks idempotent with retry backoff since delivery can duplicate, and enqueue via transaction.on_commit so workers never race an uncommitted row.",
            },
            {
                "title": "D5.7  Async Views in Django",
                "what": "Django supports async def views over ASGI - valuable for I/O-heavy views calling external services, but the ORM story keeps it nuanced.",
                "points": [
                    "async def view + ASGI server (uvicorn/daphne) = the event loop interleaves views during awaits - many concurrent slow-API calls stop eating worker processes.",
                    "Best fit: views that fan out to external HTTP services (httpx), webhooks, streaming - the same asyncio logic as FastAPI.",
                    "ORM nuance: historically sync-only; async ORM interfaces (aget, async iteration) have been arriving version by version, but parts still hop through threads (sync_to_async) - know your version.",
                    "sync_to_async wraps sync code (ORM, libraries) for async views; async_to_sync goes the other way. Mixing without them raises SynchronousOnlyOperation.",
                    "Blocking calls (requests, time.sleep) inside an async view stall the whole event loop - async libraries only.",
                    "Honest guidance: CPU-bound or ORM-heavy views gain nothing - Celery or more workers may be the simpler win; async shines on external-I/O fan-out.",
                    "Channels extends ASGI to websockets - live dashboards, notifications, chat.",
                ],
                "example": "import httpx\nasync def prices(request):\n    async with httpx.AsyncClient() as c:\n        r1, r2 = await asyncio.gather(\n            c.get(API_1), c.get(API_2))\n    return JsonResponse({...})",
                "answer": "Django runs async def views on ASGI, interleaving them at await points - a real win for views fanning out to external APIs with httpx, and Channels adds websockets. The caveats: the ORM's async support is still partial so sync_to_async bridges it, blocking calls stall the loop, and ORM/CPU-heavy views gain nothing - there Celery or worker scaling is the honest answer.",
            },
        ],
    },
]
