"""Content for React_Interview_Theory.docx.

3-YOE depth, simple English, small JSX example per topic. Function components
and hooks only (class components mentioned where interviewers still ask).
Run:  python build_docx.py react
"""

DOC_TITLE = "React Interview Theory Notes"
DOC_SUBTITLE = "3-YOE depth  |  Hooks-first + examples  |  Sanket Kolhe"

CONTENT = [
    {
        "phase": "React Phase 1 - Fundamentals",
        "topics": [
            {
                "title": "R1.1  What is React - Virtual DOM and JSX",
                "what": "React is a JavaScript library for building UIs from components; it re-renders efficiently by diffing a virtual DOM instead of touching the real DOM directly.",
                "points": [
                    "Library, not a full framework: React handles the view; routing, data fetching etc. come from the ecosystem (Router, React Query...).",
                    "Declarative model: UI = f(state). We describe what the UI looks like for a state; React updates the DOM when state changes - no manual DOM manipulation.",
                    "Virtual DOM: a lightweight JS copy of the UI tree. On state change React builds the new tree, diffs it with the old one (reconciliation), and applies only the minimal real-DOM changes - because real DOM operations are the slow part.",
                    "JSX: HTML-like syntax inside JS that compiles to function calls (React.createElement / the JSX runtime). It is just JavaScript - hence className, camelCase props and {expressions}.",
                    "Components are plain functions returning JSX; data flows one way, parent to child - predictable and debuggable.",
                    "React alone renders in the browser; Next.js adds server-side rendering; React Native maps the same model to native mobile views.",
                ],
                "example": "function App() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      Clicked {count} times\n    </button>\n  );\n}",
                "answer": "React is a component-based UI library with a declarative model - UI is a function of state. On updates it diffs a virtual DOM and patches only what changed, since real DOM writes are expensive. JSX is syntax sugar over function calls, data flows one way, and the same model powers React Native on mobile.",
            },
            {
                "title": "R1.2  Components and Props",
                "what": "A component is a reusable function returning JSX; props are the read-only inputs a parent passes down.",
                "points": [
                    "function OrderCard({ order, onCancel }) - destructured props: data plus callback functions.",
                    "Props are immutable inside the child - changing data means the PARENT changes its state and passes new props. One-way data flow.",
                    "Child talks to parent via callback props (onCancel) - the child calls it, the parent owns the logic. This pair of ideas answers most 'component communication' questions.",
                    "props.children renders whatever the parent nests inside - the composition primitive for wrappers, layouts, modals.",
                    "Component names must be Capitalized - lowercase means an HTML tag to JSX.",
                    "Default values via destructuring defaults ({ limit = 10 }); TypeScript interfaces (or PropTypes) document the contract.",
                    "Keep components small and single-purpose; extract when JSX or logic grows - reuse and testing both improve.",
                ],
                "example": "function OrderCard({ order, onCancel }) {\n  return (\n    <div className=\"card\">\n      <b>{order.id}</b> - {order.amount}\n      <button onClick={() => onCancel(order.id)}>\n        Cancel\n      </button>\n    </div>\n  );\n}",
                "answer": "Components are functions returning JSX; props are their read-only inputs flowing parent to child. Children never mutate props - they signal the parent through callback props, and the parent updates state. children enables composition, and small single-purpose components keep the tree testable.",
            },
            {
                "title": "R1.3  State - useState and Immutability",
                "what": "State is a component's own changing data; setState triggers a re-render, and updates must be immutable.",
                "points": [
                    "const [items, setItems] = useState([]) - state survives re-renders; a plain variable resets every render.",
                    "Calling the setter re-renders the component and its children with the new value.",
                    "Never mutate: items.push(x) changes the same array - React compares by reference (Object.is), sees the same reference, and may skip the re-render. Always create new: setItems([...items, x]).",
                    "Objects: setUser({ ...user, name: \"New\" }) - spread and override.",
                    "Updates are batched and asynchronous - reading state right after setting it gives the old value.",
                    "Consecutive updates need the functional form: setCount(c => c + 1) twice really adds 2; setCount(count + 1) twice adds 1 (stale value).",
                    "Lazy initialization: useState(() => expensive()) runs the initializer once, not every render.",
                ],
                "example": "const [items, setItems] = useState([]);\n// wrong: items.push(x); setItems(items)\nsetItems(prev => [...prev, x]);   // right\nsetUser(prev => ({ ...prev,\n                   name: \"Sanket\" }));",
                "answer": "useState keeps data across renders and its setter schedules a re-render. Updates must be immutable - spread into new arrays/objects - because React detects change by reference. Setters are batched, so consecutive updates use the functional form setX(prev => ...), and expensive initial values go in a lazy initializer.",
            },
            {
                "title": "R1.4  Rendering, Reconciliation and Keys",
                "what": "On state change React re-runs the component, diffs the new element tree against the old, and patches the DOM - keys tell the diff which list items are which.",
                "points": [
                    "Re-render = re-running the function to get new JSX; it does NOT mean DOM rebuild - the diff decides actual DOM work.",
                    "A parent re-render re-renders children by default (unless memoized) - worth saying, it surprises people.",
                    "Reconciliation heuristics: same element type -> update in place; different type -> unmount and rebuild the subtree.",
                    "Lists need stable keys: key lets React match old and new items, preserving state and DOM per item.",
                    "Index as key breaks on insert/remove/reorder: items shift indexes, React matches the wrong pairs - input text and animations jump to wrong rows. Use a stable id.",
                    "Key changes force remount - sometimes used deliberately (key={userId} to reset a form).",
                    "React 18 batches multiple setStates (even in promises/timeouts) into one render pass.",
                ],
                "example": "{orders.map(o => (\n  <OrderCard key={o.id} order={o} />\n))}\n// key={index} bugs: reorder/delete\n// pairs state with the wrong row",
                "answer": "State changes re-run the component and React diffs the element trees, patching only real changes - same type updates in place, different type remounts. Keys give list items identity across renders; index keys corrupt item state on reorder or delete, so I use stable ids, and a deliberate key change is a clean way to reset a subtree.",
            },
            {
                "title": "R1.5  Conditional Rendering and Lists",
                "what": "JSX composes UI with plain JS expressions - ternaries and && for conditions, map for lists.",
                "points": [
                    "Ternary for either/or: {loading ? <Spinner /> : <List items={items} />}.",
                    "&& for show/hide: {error && <Alert msg={error} />} - renders nothing when falsy.",
                    "The 0 gotcha: {items.length && <List/>} renders a literal 0 when empty - use items.length > 0 or a ternary.",
                    "Returning null renders nothing - a valid way for a component to hide itself.",
                    "Lists are map() with keys; filter().map() chains for filtered views.",
                    "Standard page pattern: three branches - loading, error, data (with an empty-state for zero items).",
                    "Heavy nesting of ternaries is a smell - extract small components or early-return variants.",
                ],
                "example": "if (loading) return <Spinner />;\nif (error) return <Alert msg={error} />;\nreturn items.length > 0 ? (\n  <ul>{items.map(i =>\n    <li key={i.id}>{i.name}</li>)}</ul>\n) : (\n  <p>No items yet</p>\n);",
                "answer": "Conditions are plain JS in JSX - ternaries for either/or, && for optional blocks (guarding the classic 0-renders bug with an explicit comparison), null to render nothing. Lists are map with stable keys, and every data view gets the loading / error / empty / data branches.",
            },
            {
                "title": "R1.6  Forms - Controlled vs Uncontrolled",
                "what": "A controlled input's value lives in React state and updates via onChange; an uncontrolled input keeps its own DOM state, read via a ref.",
                "points": [
                    "Controlled: value={name} onChange={e => setName(e.target.value)} - state is the single source of truth.",
                    "Controlled benefits: instant validation, disabling submit, formatting as-you-type, conditional fields - full control per keystroke.",
                    "Uncontrolled: defaultValue + ref, read at submit - less code, fewer re-renders, fine for simple forms; also file inputs are inherently uncontrolled.",
                    "One object state for multi-field forms: setForm({ ...form, [e.target.name]: e.target.value }).",
                    "onSubmit handler with e.preventDefault() - stop the browser page reload.",
                    "Real projects reach for react-hook-form (uncontrolled + refs = performant) with schema validation (zod/yup) - worth naming.",
                    "Every-keystroke re-renders on huge forms are the controlled approach's cost - that is exactly what react-hook-form avoids.",
                ],
                "example": "const [form, setForm] = useState({ email: \"\" });\nconst change = e => setForm({ ...form,\n  [e.target.name]: e.target.value });\n\n<form onSubmit={e => { e.preventDefault();\n                       submit(form); }}>\n  <input name=\"email\" value={form.email}\n         onChange={change} />\n</form>",
                "answer": "Controlled inputs bind value to state with onChange - the React-idiomatic way, enabling live validation and dynamic form logic at the cost of re-rendering per keystroke. Uncontrolled inputs stay in the DOM and are read via refs - simpler and faster for big or basic forms, which is why react-hook-form builds on them with schema validation on top.",
            },
            {
                "title": "R1.7  useEffect as the Lifecycle",
                "what": "useEffect runs side effects after render - with the dependency array replacing mount/update/unmount lifecycle thinking.",
                "points": [
                    "Effects are for touching the outside world: fetching, subscriptions, timers, document title - never for computing render data.",
                    "useEffect(fn, []) - after first render only (the componentDidMount analog).",
                    "useEffect(fn, [id]) - after renders where id changed.",
                    "No array - after every render (rarely wanted).",
                    "The return function is cleanup: runs before the next effect execution and at unmount - clearing timers, aborting fetches, unsubscribing.",
                    "Class mapping (asked in interviews): componentDidMount/DidUpdate/WillUnmount all collapse into effect + deps + cleanup.",
                    "StrictMode in dev mounts-unmounts-mounts once to expose missing cleanup - effects must be written idempotent.",
                    "Better mental model: 'synchronize this component with an external system whenever these values change', not 'lifecycle hooks'.",
                ],
                "example": "useEffect(() => {\n  const t = setInterval(tick, 1000);\n  return () => clearInterval(t); // cleanup\n}, []);   // mount + unmount only",
                "answer": "useEffect runs after render for outside-world work - fetching, timers, subscriptions - controlled by its dependency array: [] once, [x] when x changes. The returned cleanup runs before re-execution and at unmount, replacing all three class lifecycle methods. The real model is synchronization with external systems, and StrictMode's double-mount catches missing cleanup.",
            },
        ],
    },
    {
        "phase": "React Phase 2 - Hooks and State Management",
        "topics": [
            {
                "title": "R2.1  useEffect Deep - Dependencies, Cleanup, Common Bugs",
                "what": "Most React bugs live in effect dependency arrays - stale closures, infinite loops, and race conditions on fetches.",
                "points": [
                    "Rule: every reactive value read inside the effect belongs in the deps array - the eslint exhaustive-deps rule enforces it; silencing it hides bugs.",
                    "Stale closure: [] deps with a callback reading state - the effect captured the first render's values forever. Fix: correct deps or functional setState.",
                    "Infinite loop: effect sets state that is in its own deps, or an object/array literal in deps (new reference every render). Fix: primitives in deps, useMemo/useCallback for stable references, or restructure.",
                    "Fetch race: id changes fast, older slow response lands last and overwrites newer data. Fix: cleanup with AbortController (or an ignore flag) - cancel the stale request.",
                    "Async directly in useEffect is invalid (effect must return cleanup, not a promise) - define an inner async function and call it.",
                    "Not everything is an effect: derived data is computed in render; event logic goes in handlers. Effects are only for external synchronization.",
                ],
                "example": "useEffect(() => {\n  const ctrl = new AbortController();\n  fetch(`/api/orders/${id}`,\n        { signal: ctrl.signal })\n    .then(r => r.json())\n    .then(setOrder)\n    .catch(e => {\n      if (e.name !== \"AbortError\") setError(e);\n    });\n  return () => ctrl.abort(); // kill stale req\n}, [id]);",
                "answer": "The discipline is exhaustive deps - every value read inside goes in the array. The classic bugs: stale closures from missing deps, infinite loops from object literals in deps, and fetch races where an old response overwrites a new one - fixed with AbortController cleanup. And not everything is an effect: derived data belongs in render, event logic in handlers.",
            },
            {
                "title": "R2.2  useMemo, useCallback and React.memo",
                "what": "Three memoization tools: useMemo caches a computed value, useCallback caches a function reference, React.memo skips a child's re-render when props are unchanged.",
                "points": [
                    "useMemo(() => heavyCalc(data), [data]) - recompute only when deps change; for expensive calculations and for stabilizing object/array references.",
                    "useCallback(fn, deps) - same idea for functions; without it a new function reference is created every render.",
                    "React.memo(Child) - shallow-compares props and skips re-render if equal. But a fresh callback/object prop breaks it every time - that is WHY useCallback/useMemo exist: the three work as a set.",
                    "Reference equality is the thread joining all three - React compares by Object.is, and new references defeat every optimization.",
                    "Do not memoize everything: each has bookkeeping cost; measure with Profiler/DevTools first, optimize hot paths (big lists, heavy children).",
                    "Deps arrays follow the same exhaustive rule as effects.",
                    "React Compiler (new) aims to auto-memoize and retire most manual useMemo/useCallback - naming it shows current knowledge.",
                ],
                "example": "const filtered = useMemo(\n  () => orders.filter(o => o.status === f),\n  [orders, f]);\nconst onCancel = useCallback(\n  id => api.cancel(id), []);\nconst Card = React.memo(OrderCard);\n// stable props -> memo actually works",
                "answer": "useMemo caches values, useCallback caches function references, and React.memo skips children with unchanged props - they work as a set because memo's shallow compare dies on fresh references. I apply them on measured hot paths, not everywhere, keep deps exhaustive, and note that React Compiler is moving this memoization into the build step.",
            },
            {
                "title": "R2.3  useRef",
                "what": "useRef holds a mutable value that survives renders WITHOUT causing re-renders - used for DOM access and instance-like variables.",
                "points": [
                    "ref.current is mutable; changing it never re-renders - the opposite trade-off from state.",
                    "DOM access: <input ref={inputRef} /> then inputRef.current.focus() - focus, scroll, measure, media control.",
                    "Instance variables: interval ids, previous values, 'is first render' flags, latest-value mirrors for callbacks - anything to remember that is not display data.",
                    "Choosing: value shown in UI -> state; value only logic needs -> ref.",
                    "Do not read/write refs during render - in handlers and effects only.",
                    "Passing refs to custom components: forwardRef (pre-19) - React 19 lets ref flow as a normal prop.",
                    "useImperativeHandle exposes a controlled API (e.g. focus()) from a child to its parent - rare but asked.",
                ],
                "example": "const inputRef = useRef(null);\nconst timerRef = useRef(null);\n\nuseEffect(() => {\n  inputRef.current?.focus();\n  timerRef.current = setInterval(poll, 5000);\n  return () => clearInterval(timerRef.current);\n}, []);\n\n<input ref={inputRef} />",
                "answer": "useRef gives a mutable .current that persists across renders without triggering them - for DOM handles (focus, scroll, measure) and instance-style values like timer ids or previous state. Rule: UI data goes in state, logic-only data in refs, never touched during render. forwardRef passes refs into custom components, with React 19 making ref a plain prop.",
            },
            {
                "title": "R2.4  Custom Hooks",
                "what": "A custom hook is a use-prefixed function combining built-in hooks to package reusable stateful logic.",
                "points": [
                    "Components share UI; custom hooks share LOGIC - fetching, debouncing, localStorage sync, form handling.",
                    "Just a function calling useState/useEffect etc.; the use prefix lets lint enforce the Rules of Hooks inside.",
                    "Each component calling a hook gets its OWN independent state - hooks share logic, not data.",
                    "Rules of Hooks: call at the top level (no ifs/loops) and only from components or other hooks - call order must be stable because React tracks hooks by position.",
                    "Classic examples: useFetch(url) returning {data, loading, error}; useDebounce(value, ms) for search boxes; useLocalStorage(key).",
                    "Refactor signal: same useState+useEffect combination in two components -> extract a hook.",
                    "Hooks compose - a custom hook can use other custom hooks.",
                ],
                "example": "function useDebounce(value, ms) {\n  const [debounced, setDebounced] =\n    useState(value);\n  useEffect(() => {\n    const t = setTimeout(\n      () => setDebounced(value), ms);\n    return () => clearTimeout(t);\n  }, [value, ms]);\n  return debounced;\n}\n// const q = useDebounce(search, 400);",
                "answer": "Custom hooks package stateful logic - fetching, debouncing, storage sync - as use-prefixed functions built from other hooks. Each caller gets independent state; they share behavior, not data. They obey the Rules of Hooks (top-level, stable order), and my refactor trigger is the same state+effect pattern appearing twice.",
            },
            {
                "title": "R2.5  Context API",
                "what": "Context passes data to any depth of the tree without prop drilling - a Provider supplies, useContext consumes.",
                "points": [
                    "createContext -> <Ctx.Provider value={...}> high in the tree -> useContext(Ctx) anywhere below. No prop chains through middle components.",
                    "Right use: low-frequency global-ish data - auth user, theme, language, feature flags.",
                    "Performance catch: EVERY consumer re-renders when value changes; an inline value={{user, login}} object is a new reference each render, re-rendering all consumers - wrap in useMemo.",
                    "Split contexts by change-rate (state context vs dispatch context) so fast-changing data does not shake stable consumers.",
                    "Not a state manager by itself: no selectors, no derived subscriptions - fast-changing shared state belongs in Zustand/Redux/React Query.",
                    "Custom hook wrapper (useAuth) hides the context, adds a helpful error when the Provider is missing.",
                    "Provider composition pattern: an AuthProvider component owning state + exposing context - context and logic in one module.",
                ],
                "example": "const AuthCtx = createContext(null);\n\nfunction AuthProvider({ children }) {\n  const [user, setUser] = useState(null);\n  const value = useMemo(\n    () => ({ user, setUser }), [user]);\n  return <AuthCtx.Provider value={value}>\n           {children}\n         </AuthCtx.Provider>;\n}\nexport const useAuth = () =>\n  useContext(AuthCtx);",
                "answer": "Context solves prop drilling: a Provider high in the tree, useContext anywhere below - right for slow-changing data like the auth user or theme. Every consumer re-renders on value change, so I memoize the value object and split contexts by change-rate. For fast-changing shared state it is not enough - that is Zustand/Redux/React Query territory.",
            },
            {
                "title": "R2.6  Redux / Zustand - When Global State",
                "what": "Global state managers hold app-wide client state outside the tree - needed less often than people think, since server data belongs to React Query.",
                "points": [
                    "First split the state kinds: server cache (API data) -> React Query/SWR; local UI state -> useState; truly global client state (auth session, cart, cross-page filters) -> a store.",
                    "Redux Toolkit: single store, slices with reducers, useSelector/useDispatch; strict one-way flow, devtools time travel, middleware ecosystem. createSlice killed the old boilerplate complaint.",
                    "Selectors subscribe components to slices - only affected components re-render (vs context's all-consumers behavior).",
                    "Zustand: create() a store hook, components subscribe with selectors - tiny API, no providers, much less ceremony; my default for small/medium apps.",
                    "Redux Toolkit still wins for big teams: enforced structure, devtools, RTK Query included.",
                    "Interview shape: 'do you always need Redux?' - No: most 'global state' is server cache misfiled; React Query + a small store covers most apps.",
                ],
                "example": "const useCart = create(set => ({\n  items: [],\n  add: item => set(s =>\n    ({ items: [...s.items, item] })),\n}));\n// const items = useCart(s => s.items);",
                "answer": "I first classify state: server data goes to React Query, local UI stays in useState, and only genuine cross-page client state - session, cart, filters - earns a store. Zustand is my default for its selector-based subscriptions with no ceremony; Redux Toolkit fits bigger teams wanting enforced structure and devtools. Selectors keep re-renders scoped, unlike context.",
            },
            {
                "title": "R2.7  Lifting State Up and Composition",
                "what": "Shared state moves up to the closest common parent; composition (children and slots) keeps components flexible without prop drilling.",
                "points": [
                    "Two siblings needing the same data -> the state lives in their common parent, passed down as props with callbacks up. The fundamental React data-sharing move.",
                    "Single source of truth: never copy the same fact into two states - derive or lift instead.",
                    "Anti-pattern: mirroring props into state (useState(props.x)) - it desyncs; render from props, or derive with useMemo.",
                    "Derived state is computed, not stored: filtered lists, totals - compute in render from the source state.",
                    "Composition over configuration: pass children/JSX slots instead of a dozen boolean props - <Card header={<h2/>}>...</Card> scales; <Card showX showY.../> does not.",
                    "Component-as-prop and children-as-slot patterns replace most inheritance thinking - React has no component inheritance.",
                    "Lifting too far up causes wide re-renders - keep state as close to usage as possible; push it down when only one subtree cares.",
                ],
                "example": "function Page() {\n  const [filter, setFilter] = useState(\"\");\n  return (<>\n    <SearchBox value={filter}\n               onChange={setFilter} />\n    <OrderList filter={filter} />\n  </>);\n}  // state at the common parent",
                "answer": "When siblings share data, the state lifts to their closest common parent - one source of truth, props down, callbacks up. Derived data is computed, never duplicated into state, and mirroring props into state is the classic desync bug. For flexibility I compose with children and JSX slots instead of boolean-prop explosions, and I keep state as low in the tree as usage allows.",
            },
        ],
    },
    {
        "phase": "React Phase 3 - Ecosystem and Production",
        "topics": [
            {
                "title": "R3.1  React Router",
                "what": "React Router maps URLs to components client-side - navigation without page reloads in an SPA.",
                "points": [
                    "Setup: <BrowserRouter> wraps the app; <Routes> holds <Route path=\"/orders/:id\" element={<Order/>} />.",
                    "Dynamic segments via useParams() (the :id); query strings via useSearchParams().",
                    "<Link to>/<NavLink> navigate without reload (NavLink knows when it is active); useNavigate() for programmatic redirects after actions.",
                    "Nested routes + <Outlet/>: a Layout route renders shared chrome, children fill the outlet - dashboards in one pattern.",
                    "Protected routes: a wrapper checks auth and either renders children or <Navigate to=\"/login\" state={{from}}/> - back-to-intended-page after login.",
                    "404 via path=\"*\"; lazy route elements pair with code splitting per page.",
                    "SPA server note: the server must serve index.html for all paths, else deep-link refreshes 404 - an ops detail worth saying.",
                ],
                "example": "<Routes>\n  <Route element={<Layout />}>\n    <Route index element={<Home />} />\n    <Route path=\"orders/:id\" element={\n      <RequireAuth><Order /></RequireAuth>} />\n    <Route path=\"*\" element={<NotFound />} />\n  </Route>\n</Routes>\n// const { id } = useParams();",
                "answer": "React Router does client-side routing: Routes map paths to elements, useParams and useSearchParams read the URL, Link/useNavigate move without reloads, and nested routes with Outlet share layouts. Protected routes wrap children with an auth check redirecting to login, and the server must fall back to index.html so deep links survive refresh.",
            },
            {
                "title": "R3.2  API Calls and Data Fetching - React Query",
                "what": "Hand-rolled fetching means managing loading/error/race/cache by hand; React Query treats server data as a cache and handles all of it.",
                "points": [
                    "Manual pattern: useEffect + three states (data/loading/error) + AbortController cleanup - fine once, boilerplate at scale, and no caching: every mount refetches.",
                    "Key insight (interview gold): server data is a CACHE, not state - it can be stale, refetched, shared between components. That mental shift is why React Query exists.",
                    "useQuery({queryKey: ['orders', id], queryFn}) - dedupes identical requests, caches by key, background-refetches stale data, retries failures.",
                    "useMutation for writes + invalidateQueries to refresh affected lists after a POST/PUT - the standard update flow.",
                    "Optimistic updates: mutate UI first, roll back on error - snappy UX with safety.",
                    "staleTime (how long data is fresh) vs gcTime (how long unused cache lives) - the two knobs.",
                    "This replaces most 'global state' needs - API data no longer lives in Redux.",
                ],
                "example": "const { data, isPending, error } = useQuery({\n  queryKey: [\"orders\", page],\n  queryFn: () => api.getOrders(page),\n  staleTime: 30_000,\n});\nconst qc = useQueryClient();\nconst cancel = useMutation({\n  mutationFn: api.cancelOrder,\n  onSuccess: () => qc.invalidateQueries(\n    { queryKey: [\"orders\"] }),\n});",
                "answer": "Manually it is useEffect plus loading/error states and abort cleanup - workable but boilerplate with zero caching. React Query reframes server data as a cache keyed by queryKey: deduping, background refetch, retries; mutations invalidate affected keys, optimistic updates keep UX instant. It replaced Redux for API data in modern apps.",
            },
            {
                "title": "R3.3  Performance Optimization Checklist",
                "what": "React performance work: measure with the Profiler, cut re-render scope, virtualize big lists, shrink the bundle.",
                "points": [
                    "Measure first: React DevTools Profiler shows which components render and why; 'why did this render' beats guessing.",
                    "Cut re-render scope: push state down to the smallest subtree; memo set (React.memo/useMemo/useCallback) on measured hot paths; children pattern lets a wrapper re-render without its slot content.",
                    "Big lists: virtualization (react-window/TanStack Virtual) renders only visible rows - a 10k-row table becomes 20 DOM nodes.",
                    "Keys correct (stable ids), no inline heavy work in render, debounce fast inputs (search).",
                    "Bundle: code splitting per route, tree-shakeable imports, analyze with bundle visualizers, compress images.",
                    "Network: cache with React Query, paginate, avoid waterfalls (parallel queries).",
                    "Web Vitals framing (LCP/INP) connects React work to real UX metrics - senior signal.",
                ],
                "example": "// virtualize 10k rows\n<FixedSizeList height={600} itemCount={rows.length}\n               itemSize={40}>\n  {({ index, style }) => (\n    <Row style={style} data={rows[index]} />)}\n</FixedSizeList>",
                "answer": "I profile first with DevTools, then reduce re-render scope - state pushed down, the memo set on hot paths - virtualize long lists with react-window, keep keys stable, debounce inputs, and split the bundle per route. Data-side, React Query caching and parallel queries kill refetch waterfalls. Measured in Web Vitals, not vibes.",
            },
            {
                "title": "R3.4  Code Splitting - React.lazy and Suspense",
                "what": "Code splitting breaks the JS bundle into chunks loaded on demand - React.lazy imports a component lazily, Suspense shows a fallback while it loads.",
                "points": [
                    "Problem: one big bundle = slow first load; users download the admin panel to see the login page.",
                    "const Admin = React.lazy(() => import(\"./Admin\")) - the bundler (Vite/webpack) makes a separate chunk fetched at first render.",
                    "<Suspense fallback={<Spinner/>}> wraps lazy components - the fallback renders during the chunk fetch.",
                    "Route-level splitting is the natural cut: every page a chunk - biggest win for least effort.",
                    "Suspense boundaries can nest - page-level spinner plus widget-level ones.",
                    "Suspense is also the data-loading primitive (React Query/Next integrations) - one fallback model for code AND data.",
                    "Preloading on hover/idle hides chunk latency; error boundaries catch chunk-load failures (deploy changed hashes).",
                ],
                "example": "const Admin = React.lazy(\n  () => import(\"./pages/Admin\"));\n\n<Suspense fallback={<Spinner />}>\n  <Routes>\n    <Route path=\"/admin\"\n           element={<Admin />} />\n  </Routes>\n</Suspense>",
                "answer": "React.lazy with dynamic import splits components into on-demand chunks and Suspense renders a fallback while they load - route-level splitting gives the biggest first-load win. Boundaries nest, Suspense doubles as the data-loading primitive, and I pair it with preloading and an error boundary for failed chunk fetches after deploys.",
            },
            {
                "title": "R3.5  Error Boundaries",
                "what": "An error boundary catches render-time errors in its subtree and shows a fallback UI instead of unmounting the whole app.",
                "points": [
                    "Without one, any render error blanks the entire page - React unmounts the root.",
                    "Still class-based: componentDidCatch + getDerivedStateFromError - the one remaining class-component use (an interview fact); react-error-boundary package wraps it in a nice API.",
                    "Catches: render, lifecycle, constructor errors below it. Does NOT catch: event handlers (try/catch there), async/promise errors, server errors - name these limits.",
                    "Placement strategy: one app-level boundary + boundaries around independent widgets - a crashing chart should not kill the dashboard.",
                    "Fallback UI with a retry (reset) button; log the error to Sentry in the catch hook.",
                    "Pairs with Suspense: Suspense handles loading, error boundary handles failure - the standard pair around lazy/data components.",
                ],
                "example": "<ErrorBoundary\n  FallbackComponent={ChartError}\n  onError={logToSentry}\n  onReset={refetch}>\n  <RevenueChart />\n</ErrorBoundary>\n// chart crash != dashboard crash",
                "answer": "Error boundaries catch render errors in their subtree and swap in a fallback instead of blanking the app - still implemented via class lifecycles, usually through react-error-boundary. They miss event handlers and async errors, so those need their own handling. I place one at app level plus around independent widgets, with Sentry logging and a retry reset.",
            },
            {
                "title": "R3.6  React 18+ - Concurrent Features",
                "what": "React 18 made rendering interruptible: automatic batching everywhere, transitions for non-urgent updates, and Suspense-based patterns - with 19 adding Actions and the compiler direction.",
                "points": [
                    "Automatic batching: multiple setStates in promises/timeouts/handlers collapse into one render (pre-18 only handlers batched).",
                    "Concurrent rendering: React can pause low-priority renders to keep input responsive - the foundation under the new features.",
                    "useTransition/startTransition: mark updates non-urgent - typing stays instant while the filtered 10k-list renders when there is time; isPending shows progress.",
                    "useDeferredValue: lag a derived value behind its source - same goal, value-shaped.",
                    "createRoot is the 18 entry point enabling all of it; StrictMode double-invokes to catch unsafe effects.",
                    "React 19 direction: Actions (form submissions with pending/error built in), use() hook, Server Components (Next.js) moving data-heavy rendering server-side - naming these shows currency.",
                ],
                "example": "const [isPending, startTransition] =\n  useTransition();\n\nconst onSearch = e => {\n  setQuery(e.target.value);      // urgent\n  startTransition(() =>          // deferrable\n    setFiltered(filter(rows,\n                e.target.value)));\n};",
                "answer": "React 18 brought automatic batching everywhere and interruptible concurrent rendering: useTransition/startTransition mark heavy updates as non-urgent so typing never janks, useDeferredValue lags derived values, all enabled by createRoot. React 19 continues with Actions for forms, the use() hook, Server Components, and the compiler auto-memoizing - the ecosystem direction worth naming.",
            },
            {
                "title": "R3.7  React Native / Expo",
                "what": "React Native runs the same React model with native mobile views instead of DOM; Expo is the managed toolchain around it.",
                "points": [
                    "Same hooks, state, props - but <View>/<Text>/<FlatList> instead of div/span; styles via StyleSheet objects (flexbox default), no CSS files.",
                    "Not a webview: JS drives real native components across a bridge (new architecture: JSI/Fabric makes it near-direct calls).",
                    "Expo: SDK (camera, location, notifications), instant device preview via Expo Go, and EAS cloud builds/updates - no Xcode/Android Studio to start. Config plugins/dev-builds cover native modules; bare workflow is the escape hatch.",
                    "Navigation: react-navigation (or expo-router's file-based routes) replaces React Router - stack/tab navigators.",
                    "Lists: FlatList is virtualization built in - keyExtractor + renderItem, never map for long lists.",
                    "Platform differences via Platform.select and per-platform files; OTA updates ship JS fixes without store review.",
                    "My hands-on: the Fabric Dispatch app at Leemboodi - Expo + REST APIs to a Flask backend, real-time dispatch verification.",
                ],
                "example": "<FlatList\n  data={dispatches}\n  keyExtractor={d => d.id}\n  renderItem={({ item }) => (\n    <View style={styles.row}>\n      <Text>{item.fabric}</Text>\n    </View>\n  )}\n  onRefresh={refetch} refreshing={loading}\n/>",
                "answer": "React Native reuses React's exact component/hook model but renders real native views - View/Text/FlatList, StyleSheet flexbox, JSI bridge underneath. Expo wraps it with the SDK, instant device preview and EAS cloud builds, with dev-builds for native modules. I built Leemboodi's Fabric Dispatch app on Expo with a Flask REST backend - FlatList virtualization and react-navigation in production.",
            },
        ],
    },
]
