"""Content for SQL_Interview_Theory.docx.

Same rules as the Python notes: simple English, short sentences, theory that
can be memorised and spoken in an interview - PLUS a small example query per
topic (Sanket asked for examples on 09 Aug 2026).
Add one phase at a time, then run:  python build_docx.py sql
"""

DOC_TITLE = "SQL Interview Theory Notes"
DOC_SUBTITLE = "Simple English  |  Theory + small examples  |  Sanket Kolhe"

CONTENT = [
    {
        "phase": "SQL Phase 1 - Basics",
        "topics": [
            {
                "title": "S1.1  What is SQL, Database, DBMS vs RDBMS",
                "what": "SQL (Structured Query Language) is the standard language to store, read and manage data kept in a relational database.",
                "points": [
                    "Database: an organized collection of data. DBMS: the software that manages it (create, read, update, delete, security).",
                    "RDBMS: a DBMS that keeps data in tables (rows and columns) with relationships between tables. Examples: MySQL, PostgreSQL, SQL Server, Oracle.",
                    "Non-relational (NoSQL) systems like MongoDB or Redis store documents or key-value pairs instead of tables.",
                    "In an RDBMS, every table has columns (fields with a type) and rows (records). Tables link to each other using keys.",
                    "SQL is declarative: we say WHAT data we want, and the database engine decides HOW to fetch it.",
                    "SQL is mostly the same everywhere, with small dialect differences (LIMIT vs TOP, AUTO_INCREMENT vs SERIAL).",
                ],
                "example": "SELECT name, city FROM customers WHERE city = 'Surat';",
                "answer": "SQL is the standard declarative language for relational databases. A DBMS manages data; an RDBMS like MySQL or PostgreSQL stores it in related tables of rows and columns, linked by keys. We describe what we want, and the engine plans how to get it.",
            },
            {
                "title": "S1.2  SQL Command Types - DDL, DML, DQL, DCL, TCL",
                "what": "SQL commands are grouped by what they touch: structure, data, permissions, or transactions.",
                "points": [
                    "DDL (Data Definition Language) - changes structure: CREATE, ALTER, DROP, TRUNCATE. Usually auto-committed.",
                    "DML (Data Manipulation Language) - changes data: INSERT, UPDATE, DELETE. Can be rolled back inside a transaction.",
                    "DQL (Data Query Language) - reads data: SELECT.",
                    "DCL (Data Control Language) - permissions: GRANT, REVOKE.",
                    "TCL (Transaction Control Language) - transactions: COMMIT, ROLLBACK, SAVEPOINT.",
                    "Interview line: \"TRUNCATE is DDL, DELETE is DML\" - that is why TRUNCATE is faster and usually cannot be rolled back.",
                ],
                "example": "CREATE TABLE orders (id INT);   -- DDL\nINSERT INTO orders VALUES (1); -- DML\nSELECT * FROM orders;          -- DQL\nGRANT SELECT ON orders TO ravi;-- DCL\nCOMMIT;                        -- TCL",
                "answer": "DDL defines structure (CREATE, ALTER, DROP, TRUNCATE), DML changes data (INSERT, UPDATE, DELETE), DQL is SELECT, DCL handles permissions (GRANT, REVOKE), and TCL manages transactions (COMMIT, ROLLBACK). DELETE is DML and can roll back; TRUNCATE is DDL.",
            },
            {
                "title": "S1.3  Common Data Types",
                "what": "Every column has a data type that decides what values it can hold and how much space it takes.",
                "points": [
                    "Whole numbers: INT / BIGINT (bigger range). SMALLINT / TINYINT for small ranges.",
                    "Exact decimals: DECIMAL(10,2) - use for money, never FLOAT, because FLOAT rounds.",
                    "Approximate: FLOAT / DOUBLE - for scientific values where tiny rounding is fine.",
                    "Text: CHAR(n) fixed length, VARCHAR(n) variable up to n, TEXT for long free text.",
                    "Date and time: DATE, TIME, DATETIME / TIMESTAMP (timestamp often auto-updates and is timezone-aware in Postgres).",
                    "BOOLEAN (true/false; MySQL stores it as TINYINT(1)).",
                    "Others: JSON for flexible data, BLOB for binary files, UUID for unique ids.",
                    "Right type = less space, faster index, and built-in validation.",
                ],
                "example": "CREATE TABLE products (\n  id INT PRIMARY KEY,\n  name VARCHAR(100),\n  price DECIMAL(10,2),\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);",
                "answer": "Main families are integers (INT, BIGINT), exact decimals (DECIMAL - always for money), floats, text (CHAR, VARCHAR, TEXT), date/time (DATE, DATETIME, TIMESTAMP), boolean, and JSON/BLOB. Choosing the smallest correct type saves space and speeds up indexes.",
            },
            {
                "title": "S1.4  Constraints - NOT NULL, UNIQUE, CHECK, DEFAULT",
                "what": "A constraint is a rule on a column that the database itself enforces, so bad data can never enter.",
                "points": [
                    "NOT NULL: the column must always have a value.",
                    "UNIQUE: no two rows can have the same value in this column (NULLs are usually allowed and repeatable).",
                    "CHECK: a custom condition, like price >= 0 or status IN ('new','paid').",
                    "DEFAULT: the value used when the INSERT does not give one.",
                    "PRIMARY KEY and FOREIGN KEY are also constraints (next topic).",
                    "Why in the DB and not only in app code: many apps and scripts touch the same tables - the database is the last line of defense.",
                    "Constraints can be added later with ALTER TABLE, but existing bad data must be fixed first.",
                ],
                "example": "CREATE TABLE users (\n  email VARCHAR(255) NOT NULL UNIQUE,\n  age INT CHECK (age >= 18),\n  status VARCHAR(10) DEFAULT 'active'\n);",
                "answer": "Constraints are database-enforced rules: NOT NULL requires a value, UNIQUE forbids duplicates, CHECK applies a custom condition, DEFAULT fills missing values. They protect data quality even when many different apps write to the table.",
            },
            {
                "title": "S1.5  Primary Key vs Foreign Key",
                "what": "A primary key uniquely identifies each row in its own table; a foreign key points to a primary key in another table to connect them.",
                "points": [
                    "Primary key: unique + NOT NULL, one per table (can be one column or a composite of several). Usually an auto-increment id.",
                    "Foreign key: a column whose values must exist in the referenced table's key - this is referential integrity.",
                    "Example: orders.customer_id references customers.id - an order cannot belong to a customer that does not exist.",
                    "The DB blocks deleting a parent row that children still point to, unless we choose: ON DELETE CASCADE (delete children too), SET NULL, or RESTRICT (default block).",
                    "Foreign keys are how one-to-many and many-to-many (via a junction table) relationships are built.",
                    "Auto-increment ids: AUTO_INCREMENT (MySQL), SERIAL / IDENTITY (Postgres).",
                ],
                "example": "CREATE TABLE orders (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  customer_id INT,\n  FOREIGN KEY (customer_id) REFERENCES customers(id)\n    ON DELETE CASCADE\n);",
                "answer": "A primary key is the unique, non-null identifier of a row; a foreign key stores another table's primary key to link rows and enforce referential integrity - the DB rejects orphan records, and ON DELETE CASCADE/SET NULL/RESTRICT controls what happens when the parent goes.",
            },
            {
                "title": "S1.6  NULL - Behavior, IS NULL, COALESCE",
                "what": "NULL means \"value unknown or missing\". It is not zero, not an empty string, and it behaves specially in every comparison.",
                "points": [
                    "Any comparison with NULL gives NULL (unknown), not true or false: salary = NULL never matches.",
                    "Correct check: IS NULL / IS NOT NULL.",
                    "NULL = NULL is also unknown - two unknowns are not \"equal\".",
                    "Aggregates skip NULLs: COUNT(col) ignores them, but COUNT(*) counts every row. AVG divides only by non-null count.",
                    "NOT IN with a NULL inside the list matches nothing - a classic silent bug.",
                    "COALESCE(a, b, c) returns the first non-null value - the standard way to give defaults in queries.",
                    "In WHERE, rows with NULL in the condition simply drop out - they are neither true nor false.",
                ],
                "example": "SELECT name, COALESCE(phone, 'no phone') AS phone\nFROM customers\nWHERE deleted_at IS NULL;",
                "answer": "NULL means unknown, so any comparison with it returns unknown - we must use IS NULL, not = NULL. Aggregates like COUNT(col) and AVG skip NULLs, NOT IN breaks silently if the list contains a NULL, and COALESCE gives the first non-null value as a default.",
            },
        ],
    },
    {
        "phase": "SQL Phase 2 - Core Queries",
        "topics": [
            {
                "title": "S2.1  SELECT, WHERE and Operators (IN, BETWEEN, LIKE)",
                "what": "SELECT chooses columns, FROM names the table, and WHERE filters rows with conditions.",
                "points": [
                    "SELECT * takes all columns - fine for exploring, avoided in production code (wastes I/O, breaks when columns change).",
                    "Comparison operators: =, <> (not equal), >, <, >=, <=. Combine with AND, OR, NOT - use brackets to keep OR logic clear.",
                    "IN: value matches any item in a list - cleaner than many ORs.",
                    "BETWEEN a AND b: inclusive range, works for numbers and dates.",
                    "LIKE with wildcards: % = any characters, _ = exactly one. 'Sa%' starts with Sa. ILIKE in Postgres ignores case.",
                    "Logical order of a query: FROM -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY -> LIMIT. (That is why WHERE cannot see SELECT aliases.)",
                ],
                "example": "SELECT name, price FROM products\nWHERE category IN ('shirt','kurti')\n  AND price BETWEEN 500 AND 2000\n  AND name LIKE 'Cotton%';",
                "answer": "SELECT picks columns and WHERE filters rows using =, <>, IN for lists, BETWEEN for inclusive ranges, and LIKE with % and _ wildcards for patterns. Logically the engine runs FROM, WHERE, GROUP BY, HAVING, SELECT, then ORDER BY - which explains why WHERE cannot use SELECT aliases.",
            },
            {
                "title": "S2.2  DISTINCT, ORDER BY, LIMIT / OFFSET",
                "what": "DISTINCT removes duplicate rows, ORDER BY sorts the result, and LIMIT/OFFSET take just a slice of it.",
                "points": [
                    "SELECT DISTINCT city FROM customers - each city once. It applies to the whole selected row, not one column alone.",
                    "COUNT(DISTINCT city) counts unique values.",
                    "ORDER BY col ASC|DESC; multiple keys allowed: ORDER BY city, price DESC. Without ORDER BY, row order is never guaranteed.",
                    "Sorting can also use expressions or aliases: ORDER BY total DESC.",
                    "LIMIT n returns the first n rows; OFFSET m skips m first - together they give pagination (page 3 of size 20: LIMIT 20 OFFSET 40).",
                    "Dialects: MySQL/Postgres use LIMIT; SQL Server uses TOP n or OFFSET ... FETCH.",
                    "Big OFFSETs get slow (engine still walks the skipped rows) - keyset pagination (WHERE id > last_seen) scales better.",
                ],
                "example": "SELECT DISTINCT city FROM customers;\n\nSELECT name, price FROM products\nORDER BY price DESC\nLIMIT 10 OFFSET 20;   -- page 3, 10 per page",
                "answer": "DISTINCT de-duplicates the selected rows, ORDER BY sorts (multiple keys, ASC/DESC), and LIMIT with OFFSET slices for pagination. Row order is undefined without ORDER BY, and for deep pages keyset pagination beats large OFFSETs.",
            },
            {
                "title": "S2.3  Aggregate Functions - COUNT, SUM, AVG, MIN, MAX",
                "what": "Aggregate functions squeeze many rows into one summary value.",
                "points": [
                    "COUNT(*) counts rows; COUNT(col) counts non-null values in that column; COUNT(DISTINCT col) counts unique values.",
                    "SUM adds, AVG averages, MIN/MAX give extremes (also work on text and dates).",
                    "All except COUNT(*) ignore NULLs - AVG divides by the non-null count only.",
                    "Without GROUP BY, the whole result is one row.",
                    "An aggregate cannot go in WHERE (WHERE runs before grouping) - filtering on aggregates belongs in HAVING.",
                    "Mixing aggregated and normal columns needs GROUP BY on the normal ones.",
                ],
                "example": "SELECT COUNT(*) AS orders_count,\n       SUM(amount) AS revenue,\n       AVG(amount) AS avg_order,\n       MAX(amount) AS biggest\nFROM orders\nWHERE status = 'paid';",
                "answer": "COUNT, SUM, AVG, MIN and MAX collapse many rows into one summary. COUNT(*) counts rows while COUNT(col) skips NULLs, all aggregates ignore NULLs otherwise, and conditions on aggregates go in HAVING because WHERE runs before aggregation.",
            },
            {
                "title": "S2.4  GROUP BY and HAVING",
                "what": "GROUP BY makes one summary row per group, and HAVING filters those groups after aggregation.",
                "points": [
                    "GROUP BY city gives one row per city; aggregates then work inside each group.",
                    "Rule: every column in SELECT must be either aggregated or listed in GROUP BY.",
                    "WHERE filters rows BEFORE grouping; HAVING filters groups AFTER - both can appear in one query.",
                    "HAVING can use aggregates: HAVING COUNT(*) > 5. WHERE cannot.",
                    "Grouping by several columns makes one row per combination: GROUP BY city, category.",
                    "Order of writing: FROM, WHERE, GROUP BY, HAVING, ORDER BY.",
                    "Put as much filtering as possible into WHERE - fewer rows to group means a faster query.",
                ],
                "example": "SELECT city, COUNT(*) AS customers\nFROM customers\nWHERE status = 'active'\nGROUP BY city\nHAVING COUNT(*) >= 10\nORDER BY customers DESC;",
                "answer": "GROUP BY collapses rows into one row per group so aggregates work per group, and HAVING filters those groups on aggregate conditions. WHERE filters rows before grouping, HAVING after - and pushing filters into WHERE keeps queries fast.",
            },
            {
                "title": "S2.5  Common String and Date Functions",
                "what": "Built-in functions transform text and dates right inside the query.",
                "points": [
                    "Text: CONCAT joins, UPPER/LOWER change case, TRIM cuts spaces, LENGTH counts, SUBSTRING cuts a part, REPLACE swaps text.",
                    "Search inside text: LOCATE/POSITION or LIKE.",
                    "Dates: NOW()/CURRENT_TIMESTAMP for current moment, CURRENT_DATE for today.",
                    "Parts of a date: EXTRACT(YEAR FROM col) or YEAR(col)/MONTH(col) in MySQL.",
                    "Date maths: DATE_ADD/DATE_SUB (MySQL), col + INTERVAL '7 days' (Postgres), DATEDIFF for gaps.",
                    "Formatting: DATE_FORMAT (MySQL) / TO_CHAR (Postgres) turn dates into display text.",
                    "Careful: wrapping an indexed column in a function (WHERE YEAR(created_at) = 2026) blocks the index - better use a range: created_at >= '2026-01-01' AND < '2027-01-01'.",
                ],
                "example": "SELECT CONCAT(first_name, ' ', last_name) AS full_name,\n       UPPER(city) AS city,\n       EXTRACT(YEAR FROM created_at) AS joined_year\nFROM customers\nWHERE created_at >= NOW() - INTERVAL '30 days';",
                "answer": "Everyday functions: CONCAT, UPPER/LOWER, TRIM, SUBSTRING, REPLACE for text; NOW, EXTRACT, DATE_ADD/INTERVAL, DATEDIFF for dates. One performance rule: never wrap an indexed column in a function inside WHERE - rewrite it as a range so the index still works.",
            },
            {
                "title": "S2.6  CASE Expression",
                "what": "CASE is SQL's if/else - it returns different values based on conditions, inside any query.",
                "points": [
                    "Searched form: CASE WHEN cond1 THEN x WHEN cond2 THEN y ELSE z END. Conditions are checked top to bottom, first match wins.",
                    "Simple form: CASE status WHEN 'P' THEN 'Paid' WHEN 'N' THEN 'New' END - compares one column to values.",
                    "Without ELSE, non-matching rows get NULL.",
                    "Works in SELECT (labels/buckets), ORDER BY (custom sort order), and inside aggregates.",
                    "Conditional counting trick: SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END) - counts per condition in one pass; FILTER (Postgres) does the same.",
                    "This pivot-style trick turns row values into columns - a very common interview ask.",
                ],
                "example": "SELECT name,\n  CASE\n    WHEN price < 500 THEN 'budget'\n    WHEN price < 2000 THEN 'regular'\n    ELSE 'premium'\n  END AS price_band\nFROM products;",
                "answer": "CASE is an inline if/else: WHEN conditions are checked in order and the first match returns its value, ELSE catches the rest. I use it for bucketing values, custom sort orders, and the SUM(CASE WHEN...) trick to count several conditions in a single scan.",
            },
        ],
    },
    {
        "phase": "SQL Phase 3 - Joins and Subqueries",
        "topics": [
            {
                "title": "S3.1  What is a JOIN + INNER JOIN",
                "what": "A JOIN combines rows from two tables using a matching condition, usually a foreign key equals a primary key.",
                "points": [
                    "Relational data is split into tables (customers, orders) - JOIN brings related rows back together for reading.",
                    "The ON clause gives the match condition: ON o.customer_id = c.id.",
                    "INNER JOIN returns only rows that match on BOTH sides - customers without orders and orders without customers disappear.",
                    "Plain JOIN means INNER JOIN.",
                    "Table aliases (customers c) keep queries short; needed when the same column name exists on both sides.",
                    "Joining on more than one condition or joining 3+ tables just chains more JOIN ... ON blocks.",
                ],
                "example": "SELECT c.name, o.amount\nFROM customers c\nINNER JOIN orders o ON o.customer_id = c.id\nWHERE o.status = 'paid';",
                "answer": "A JOIN merges rows of two tables on a condition, typically foreign key = primary key. INNER JOIN keeps only matching rows from both sides - non-matching rows are dropped. Aliases and chained JOIN...ON blocks handle multi-table queries.",
            },
            {
                "title": "S3.2  LEFT, RIGHT and FULL OUTER JOIN",
                "what": "Outer joins keep rows even when there is no match: LEFT keeps all left rows, RIGHT all right rows, FULL keeps both sides.",
                "points": [
                    "LEFT JOIN: every left-table row appears; where no match exists, the right side's columns come back as NULL.",
                    "Classic use: all customers with their orders, INCLUDING customers who never ordered.",
                    "\"Find rows with no match\" pattern: LEFT JOIN ... WHERE right.id IS NULL - e.g. customers with zero orders.",
                    "RIGHT JOIN is the mirror; in practice people just swap table order and use LEFT.",
                    "FULL OUTER JOIN keeps unmatched rows of both sides (Postgres/SQL Server have it; MySQL fakes it with LEFT UNION RIGHT).",
                    "Careful: putting right-table conditions in WHERE turns a LEFT JOIN into an INNER JOIN - put them in ON to keep the outer behavior.",
                ],
                "example": "-- customers who never ordered\nSELECT c.name\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nWHERE o.id IS NULL;",
                "answer": "LEFT JOIN keeps every left row and fills missing right columns with NULL, RIGHT is the mirror, FULL keeps both sides. The LEFT JOIN + IS NULL pattern finds rows without a match, and right-side filters must go in ON, not WHERE, or the join silently becomes inner.",
            },
            {
                "title": "S3.3  CROSS JOIN and SELF JOIN",
                "what": "CROSS JOIN pairs every row with every row (no condition); SELF JOIN joins a table to itself.",
                "points": [
                    "CROSS JOIN output size = rows(A) x rows(B) - the Cartesian product. 1,000 x 1,000 = 1,000,000 rows, so use carefully.",
                    "Real cross-join uses: generating combinations - all sizes x all colors, all dates x all stores for reports.",
                    "An accidental cross join happens when the ON/WHERE condition is forgotten in old comma-style joins.",
                    "SELF JOIN: the same table twice with two aliases - it is how rows of one table relate to each other.",
                    "Classic self-join cases: employee and manager (manager_id points to the same table), finding duplicate rows, comparing a row with the previous one.",
                    "Nothing special in syntax - just aliases make the two copies distinct.",
                ],
                "example": "-- employee with manager name (same table)\nSELECT e.name AS employee, m.name AS manager\nFROM employees e\nLEFT JOIN employees m ON e.manager_id = m.id;",
                "answer": "CROSS JOIN gives the Cartesian product - every combination, size A times B - useful for generating combinations, dangerous by accident. SELF JOIN uses two aliases of one table to relate its own rows, like employee-manager hierarchies or duplicate detection.",
            },
            {
                "title": "S3.4  UNION vs UNION ALL",
                "what": "Both stack results of two queries vertically; UNION removes duplicate rows, UNION ALL keeps everything.",
                "points": [
                    "Requirement: both SELECTs must have the same number of columns with compatible types. Column names come from the first query.",
                    "UNION sorts/hashes to remove duplicates - extra work, slower.",
                    "UNION ALL just appends - faster; use it whenever duplicates are impossible or acceptable.",
                    "Use cases: same-shaped data from two tables (this year + archive), combining different WHERE branches.",
                    "ORDER BY applies once, at the very end of the whole union.",
                    "Related set operators: INTERSECT (common rows) and EXCEPT/MINUS (rows in A not in B) - not in MySQL.",
                    "JOIN combines horizontally (more columns); UNION stacks vertically (more rows).",
                ],
                "example": "SELECT name, amount FROM orders_2026\nUNION ALL\nSELECT name, amount FROM orders_archive\nORDER BY amount DESC;",
                "answer": "UNION stacks two same-shaped results and removes duplicates; UNION ALL keeps them and is faster, so it is my default when duplicates cannot occur. JOIN widens with columns, UNION lengthens with rows; INTERSECT and EXCEPT are the sibling set operators.",
            },
            {
                "title": "S3.5  Subqueries - Single Row, Multi Row, Correlated",
                "what": "A subquery is a query inside another query - in WHERE, FROM or SELECT.",
                "points": [
                    "Single-row subquery returns one value: WHERE price > (SELECT AVG(price) FROM products).",
                    "Multi-row subquery returns a list - pair it with IN, ANY or ALL.",
                    "A subquery in FROM is a derived table - it needs an alias and acts like a temporary table.",
                    "A scalar subquery in SELECT adds a computed column per row.",
                    "Plain subqueries run once. A CORRELATED subquery references the outer row, so it conceptually re-runs per outer row - powerful, often slower.",
                    "Correlated example: each product priced above ITS category average.",
                    "Many subqueries can be rewritten as JOINs; modern optimizers often do this internally, but the JOIN version is easier to read and index.",
                ],
                "example": "-- products costlier than their category's average\nSELECT name FROM products p\nWHERE price > (SELECT AVG(price)\n               FROM products\n               WHERE category = p.category);",
                "answer": "Subqueries nest a query in WHERE, FROM or SELECT: single-row ones feed comparisons, multi-row ones feed IN/ANY/ALL, FROM-subqueries act as derived tables. A correlated subquery references the outer row and logically runs per row - readable but worth rewriting as a JOIN when it is slow.",
            },
            {
                "title": "S3.6  EXISTS vs IN",
                "what": "Both check membership against another query; EXISTS asks \"is there at least one matching row?\", IN compares against the returned list.",
                "points": [
                    "EXISTS (SELECT 1 ...) stops at the first match - it never builds the full list. What is selected inside does not matter.",
                    "IN materializes the subquery list, then compares.",
                    "The NULL trap again: NOT IN returns nothing if the subquery list contains a NULL. NOT EXISTS is safe - prefer it for \"not in other table\" checks.",
                    "Performance: on large subquery results EXISTS usually wins; on small fixed lists IN is fine and reads nicely.",
                    "EXISTS is naturally correlated: the inner query references the outer row.",
                    "Modern optimizers often make them equal - but the NOT IN NULL bug is about correctness, not speed, so the rule stays.",
                ],
                "example": "-- customers who have at least one paid order\nSELECT name FROM customers c\nWHERE EXISTS (SELECT 1 FROM orders o\n              WHERE o.customer_id = c.id\n                AND o.status = 'paid');",
                "answer": "EXISTS checks if the subquery finds at least one row and short-circuits; IN builds the whole list first. For negative checks I always use NOT EXISTS, because NOT IN silently returns nothing when the list contains a NULL.",
            },
        ],
    },
    {
        "phase": "SQL Phase 4 - Advanced",
        "topics": [
            {
                "title": "S4.1  Indexes",
                "what": "An index is a sorted lookup structure (usually a B-tree) that lets the database find rows without scanning the whole table.",
                "points": [
                    "Like a book index: instead of reading every page, jump straight to the entry. Search drops from O(n) full scan to O(log n).",
                    "Primary keys and unique constraints get indexes automatically; add others with CREATE INDEX on columns used in WHERE, JOIN and ORDER BY.",
                    "Composite index (city, price): order matters - it serves filters on city, or city+price, but NOT price alone (leftmost prefix rule).",
                    "Cost: every INSERT/UPDATE/DELETE must also update each index, and indexes take disk - do not index everything.",
                    "Index is skipped when: the column is wrapped in a function, leading-wildcard LIKE '%text', or the column has few distinct values (low selectivity).",
                    "A covering index contains every column the query needs - the table itself is never touched.",
                    "EXPLAIN shows whether a query uses an index or does a full table scan - the first tool for slow queries.",
                ],
                "example": "CREATE INDEX idx_orders_customer\n  ON orders (customer_id, created_at);\n\nEXPLAIN SELECT * FROM orders\nWHERE customer_id = 42\nORDER BY created_at DESC;",
                "answer": "An index is a B-tree that makes lookups O(log n) instead of a full scan - I add them on WHERE/JOIN/ORDER BY columns. Composite indexes follow the leftmost-prefix rule, writes get slower per index, functions and leading wildcards defeat them, and EXPLAIN confirms usage.",
            },
            {
                "title": "S4.2  Views",
                "what": "A view is a saved SELECT query that we can use like a table.",
                "points": [
                    "CREATE VIEW active_customers AS SELECT ... - later just SELECT * FROM active_customers.",
                    "A normal view stores no data - the query runs fresh each time, so data is always current.",
                    "Uses: hide complex joins behind a simple name, reuse logic, and security - grant access to the view (chosen columns/rows) instead of the raw table.",
                    "Simple one-table views can be updatable; views with joins, aggregates or DISTINCT are read-only.",
                    "A MATERIALIZED view (Postgres/Oracle) stores the result physically - fast reads for heavy dashboards, but it needs REFRESH and can go stale.",
                    "Views stack: a view can select from another view - keep it shallow or debugging hurts.",
                ],
                "example": "CREATE VIEW city_revenue AS\nSELECT c.city, SUM(o.amount) AS revenue\nFROM customers c\nJOIN orders o ON o.customer_id = c.id\nGROUP BY c.city;\n\nSELECT * FROM city_revenue WHERE revenue > 100000;",
                "answer": "A view is a stored query used like a table - no data of its own, always fresh, great for hiding join complexity and restricting access. Materialized views store results physically for speed but must be refreshed as they go stale.",
            },
            {
                "title": "S4.3  Stored Procedures and Triggers",
                "what": "A stored procedure is saved SQL logic executed on demand; a trigger is logic that fires automatically on INSERT, UPDATE or DELETE.",
                "points": [
                    "Procedure: named block with parameters, loops and conditions, run with CALL. Lives inside the database.",
                    "Benefits: one round trip for multi-step logic, central logic shared by all apps, tight permission control.",
                    "Downsides: harder to version-control, test and debug than app code - modern teams keep heavy business logic in the application.",
                    "A stored FUNCTION returns a value and can be used inside queries; a procedure is called standalone.",
                    "Trigger: BEFORE or AFTER + INSERT/UPDATE/DELETE on a table - runs per statement or per row (FOR EACH ROW). OLD and NEW give the row values.",
                    "Trigger uses: audit logs, updated_at stamps, enforcing rules across tables.",
                    "Trigger risks: hidden behavior (\"why did this column change?!\"), chains of triggers, slow bulk writes - use sparingly and document.",
                ],
                "example": "CREATE TRIGGER trg_updated\nBEFORE UPDATE ON products\nFOR EACH ROW\nSET NEW.updated_at = NOW();",
                "answer": "Stored procedures keep multi-step SQL logic inside the database, callable with parameters in one round trip; functions return values usable in queries. Triggers fire automatically before/after row changes - good for audit trails and timestamps, but they hide behavior, so I keep them minimal.",
            },
            {
                "title": "S4.4  Transactions and ACID",
                "what": "A transaction groups several statements into one all-or-nothing unit, and ACID are the four guarantees that make it safe.",
                "points": [
                    "BEGIN ... COMMIT makes changes permanent together; ROLLBACK undoes everything since BEGIN.",
                    "Classic example: money transfer - debit one account, credit another; both happen or neither.",
                    "Atomicity: all-or-nothing - a failure in the middle leaves no half-done work.",
                    "Consistency: every transaction moves the DB from one valid state to another - constraints hold before and after.",
                    "Isolation: concurrent transactions do not see each other's half-done work (levels in next topic).",
                    "Durability: once committed, data survives crashes - written to disk/log first.",
                    "SAVEPOINT allows partial rollback inside a long transaction.",
                    "Keep transactions short - long ones hold locks and block other sessions.",
                ],
                "example": "BEGIN;\nUPDATE accounts SET balance = balance - 500 WHERE id = 1;\nUPDATE accounts SET balance = balance + 500 WHERE id = 2;\nCOMMIT;   -- or ROLLBACK on any error",
                "answer": "A transaction is an all-or-nothing group of statements between BEGIN and COMMIT, reversible with ROLLBACK. ACID: Atomicity (no half-done work), Consistency (constraints always hold), Isolation (concurrent transactions don't see partial work), Durability (committed data survives crashes).",
            },
            {
                "title": "S4.5  Isolation Levels and Concurrency Problems",
                "what": "Isolation levels trade correctness against speed when many transactions run at once, by allowing or blocking three read problems.",
                "points": [
                    "Dirty read: seeing another transaction's UNCOMMITTED change - worst problem.",
                    "Non-repeatable read: same row read twice gives different values, because someone committed in between.",
                    "Phantom read: same WHERE run twice returns new/missing ROWS, because someone inserted or deleted.",
                    "READ UNCOMMITTED: allows all three (rarely used).",
                    "READ COMMITTED: blocks dirty reads - default in Postgres, Oracle, SQL Server.",
                    "REPEATABLE READ: also blocks non-repeatable reads - MySQL InnoDB default (InnoDB largely prevents phantoms too via MVCC).",
                    "SERIALIZABLE: blocks everything - as if transactions ran one by one; safest, slowest.",
                    "Engines implement this with MVCC (row versions) rather than pure locking - readers do not block writers.",
                ],
                "example": "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;\nBEGIN;\nSELECT balance FROM accounts WHERE id = 1;\n-- ... same SELECT later returns the same value\nCOMMIT;",
                "answer": "The three problems are dirty, non-repeatable and phantom reads. READ UNCOMMITTED allows all, READ COMMITTED stops dirty reads (Postgres default), REPEATABLE READ also fixes re-reads (MySQL default), SERIALIZABLE stops phantoms too. Higher isolation = safer but slower; MVCC makes it efficient.",
            },
            {
                "title": "S4.6  Window Functions - ROW_NUMBER, RANK, PARTITION BY",
                "what": "A window function computes a value across related rows WITHOUT collapsing them - every row stays, with an extra calculated column.",
                "points": [
                    "Syntax: func() OVER (PARTITION BY group_col ORDER BY sort_col). PARTITION BY = groups, but rows remain individual.",
                    "ROW_NUMBER(): 1,2,3... per partition - no ties.",
                    "RANK(): ties share a rank and a gap follows (1,1,3). DENSE_RANK(): ties share, no gap (1,1,2).",
                    "Top-N per group - THE classic interview question: number rows per group, keep rn <= N.",
                    "LAG/LEAD read the previous/next row - month-over-month comparisons without self-joins.",
                    "SUM/AVG/COUNT as window functions give running totals: SUM(amount) OVER (ORDER BY date).",
                    "Window functions run after WHERE/GROUP BY - filter on them via a subquery or CTE, not directly in WHERE.",
                ],
                "example": "-- top 2 costliest products per category\nSELECT * FROM (\n  SELECT name, category, price,\n    ROW_NUMBER() OVER (PARTITION BY category\n                       ORDER BY price DESC) AS rn\n  FROM products\n) t WHERE rn <= 2;",
                "answer": "Window functions calculate over a partition while keeping every row - OVER (PARTITION BY ... ORDER BY ...). ROW_NUMBER numbers uniquely, RANK leaves gaps on ties, DENSE_RANK does not, LAG/LEAD reach neighboring rows, and aggregates over a window give running totals. Top-N per group is the classic use.",
            },
            {
                "title": "S4.7  CTE - WITH Clause",
                "what": "A CTE (Common Table Expression) is a named temporary result defined with WITH, used like a table inside one query.",
                "points": [
                    "WITH big_orders AS (SELECT ...) SELECT ... FROM big_orders - reads top-down, unlike nested subqueries.",
                    "Several CTEs chain in one WITH, each able to use the previous - a step-by-step pipeline.",
                    "Same power as a derived table in FROM, but far more readable, and referenced multiple times by name.",
                    "RECURSIVE CTEs walk hierarchies: base query UNION ALL a query that references the CTE itself - org charts, category trees, graph paths.",
                    "Lifetime: only inside its single statement - unlike a view (permanent) or temp table (session).",
                    "The standard partner of window functions: compute in the CTE, filter outside.",
                ],
                "example": "WITH city_rev AS (\n  SELECT city, SUM(amount) AS revenue\n  FROM orders GROUP BY city\n)\nSELECT * FROM city_rev\nWHERE revenue > (SELECT AVG(revenue) FROM city_rev);",
                "answer": "A CTE is a named temporary result via WITH, making multi-step queries read top-down and reusable within the statement. Recursive CTEs handle trees like org charts. It lives only for that one query - lighter than a view or temp table.",
            },
            {
                "title": "S4.8  Normalization - 1NF, 2NF, 3NF and Denormalization",
                "what": "Normalization organizes tables to remove duplicate data, so each fact is stored exactly once.",
                "points": [
                    "Problems it solves: update anomalies (change an address in 50 rows), insert/delete anomalies, wasted space.",
                    "1NF: atomic values - no comma-separated lists in a cell, no repeating columns; every row unique.",
                    "2NF: 1NF + no partial dependency - with a composite key, every non-key column must depend on the WHOLE key, not part of it.",
                    "3NF: 2NF + no transitive dependency - non-key columns must not depend on other non-key columns (customer_city depends on customer, not on order).",
                    "Practical summary: \"every non-key column depends on the key, the whole key, and nothing but the key\".",
                    "Higher forms exist (BCNF...) but 3NF is the practical target for OLTP systems.",
                    "Denormalization: deliberately duplicating data (e.g. storing total in orders) to make reads faster - standard in reporting/analytics, paid for with careful sync on writes.",
                ],
                "example": "-- 3NF: split city out of orders\ncustomers(id, name, city)\norders(id, customer_id, amount)\n-- denormalized for reports:\norders_report(order_id, customer_name, city, amount)",
                "answer": "Normalization removes duplication: 1NF atomic values, 2NF full-key dependency, 3NF no non-key-to-non-key dependency - \"the key, the whole key, nothing but the key\". OLTP schemas target 3NF; analytics often denormalizes on purpose, trading duplicate data for read speed.",
            },
        ],
    },
    {
        "phase": "SQL Phase 5 - Interview Favourites",
        "topics": [
            {
                "title": "S5.1  DELETE vs TRUNCATE vs DROP",
                "what": "DELETE removes chosen rows, TRUNCATE empties the whole table fast, DROP removes the table itself.",
                "points": [
                    "DELETE: DML, works with WHERE, fires triggers, logs each row, can ROLLBACK. Slow on huge tables.",
                    "TRUNCATE: DDL, no WHERE - always the whole table. Deallocates pages instead of logging rows, so it is very fast; usually resets auto-increment; triggers do not fire; rollback support varies (Postgres yes inside a transaction, MySQL no).",
                    "DROP: DDL, deletes data + structure + indexes + constraints. The table is gone.",
                    "Speed: DROP/TRUNCATE fast, DELETE row-by-row.",
                    "Choose: some rows -> DELETE with WHERE; empty the table but keep it -> TRUNCATE; remove the table entirely -> DROP.",
                    "Foreign keys can block TRUNCATE on referenced tables.",
                ],
                "example": "DELETE FROM orders WHERE status = 'cancelled';\nTRUNCATE TABLE temp_import;\nDROP TABLE old_backup;",
                "answer": "DELETE is row-wise DML with WHERE and rollback, TRUNCATE is DDL that instantly empties the whole table and typically resets auto-increment without firing triggers, DROP removes the table structure itself. Rows -> DELETE, empty-but-keep -> TRUNCATE, remove completely -> DROP.",
            },
            {
                "title": "S5.2  WHERE vs HAVING",
                "what": "WHERE filters individual rows before grouping; HAVING filters groups after aggregation.",
                "points": [
                    "Execution order: FROM -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY.",
                    "WHERE cannot contain aggregate functions - at that stage groups do not exist yet.",
                    "HAVING can: HAVING COUNT(*) > 5, HAVING SUM(amount) > 10000.",
                    "Both often appear together: WHERE narrows the rows, HAVING filters the summarized groups.",
                    "Performance rule: every condition that CAN go in WHERE SHOULD - fewer rows reach the grouping stage.",
                    "HAVING without GROUP BY treats the whole result as one group (rare but legal).",
                ],
                "example": "SELECT category, AVG(price) AS avg_price\nFROM products\nWHERE in_stock = 1        -- rows first\nGROUP BY category\nHAVING AVG(price) > 1000; -- then groups",
                "answer": "WHERE runs before grouping and filters rows, so it cannot use aggregates; HAVING runs after GROUP BY and filters groups on aggregate results. I push every possible condition into WHERE for speed and keep only aggregate conditions in HAVING.",
            },
            {
                "title": "S5.3  Primary Key vs Unique Key",
                "what": "Both enforce uniqueness; the primary key is the table's single main identifier and rejects NULL, while unique keys can be many and allow NULLs.",
                "points": [
                    "Primary key: exactly one per table, NOT NULL forced, the target foreign keys reference.",
                    "Unique key/constraint: many allowed per table, NULLs permitted (MySQL/Postgres allow multiple NULLs; SQL Server only one).",
                    "Both are backed by an index automatically.",
                    "In InnoDB (MySQL) the primary key is also the clustered index - the physical row order - so a small, stable PK matters.",
                    "Typical pattern: auto-increment id as PK, plus UNIQUE on natural fields like email or username.",
                    "Composite versions exist for both (PRIMARY KEY (a, b) / UNIQUE (a, b)).",
                ],
                "example": "CREATE TABLE users (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  email VARCHAR(255) UNIQUE,\n  phone VARCHAR(15) UNIQUE\n);",
                "answer": "A table has one primary key - unique, NOT NULL, referenced by foreign keys, and in InnoDB the clustered index - but can have many unique keys, which allow NULLs. Common design: surrogate id as PK plus UNIQUE constraints on natural fields like email.",
            },
            {
                "title": "S5.4  CHAR vs VARCHAR vs TEXT",
                "what": "All store text: CHAR is fixed length, VARCHAR is variable with a limit, TEXT is for long content.",
                "points": [
                    "CHAR(10): always 10 characters - shorter values are space-padded. Best for truly fixed codes: country 'IN', PIN codes, flags.",
                    "VARCHAR(n): stores actual length + a small length byte, up to n. The default choice for names, emails, titles.",
                    "TEXT: long free text (descriptions, logs). In MySQL it may live off-page, cannot have a DEFAULT, and index needs a prefix length.",
                    "CHAR can be marginally faster for fixed-width data; VARCHAR saves space for variable data.",
                    "VARCHAR(n): n is a character limit and acts as free validation - do not declare VARCHAR(10000) \"just in case\".",
                    "Sorting/comparison behavior is governed by collation (case sensitivity, language rules) for all three.",
                ],
                "example": "CREATE TABLE items (\n  code CHAR(2),           -- 'IN', 'US'\n  name VARCHAR(100),\n  description TEXT\n);",
                "answer": "CHAR(n) is fixed-length and padded - right for constant-width codes; VARCHAR(n) stores actual length up to a cap - the default for normal fields; TEXT holds long content but with index and default-value limits in MySQL. Pick the smallest sensible type.",
            },
            {
                "title": "S5.5  Nth Highest Salary - The Approaches",
                "what": "A classic question with three standard approaches: LIMIT OFFSET, window functions, or a correlated subquery.",
                "points": [
                    "Approach 1 - LIMIT/OFFSET: SELECT DISTINCT salary ORDER BY salary DESC LIMIT 1 OFFSET n-1. Simple; DISTINCT handles duplicate salaries.",
                    "Approach 2 - window function (best answer today): DENSE_RANK() OVER (ORDER BY salary DESC), filter rank = n in an outer query.",
                    "DENSE_RANK vs RANK matters with ties: dense counts distinct salary levels, rank skips positions after ties - say this in the interview.",
                    "Approach 3 - correlated subquery (classic, works everywhere): the nth highest has exactly n-1 distinct salaries above it.",
                    "Per-department versions just add PARTITION BY department to the window.",
                    "Mention edge cases for extra points: fewer than n distinct salaries -> empty result / NULL.",
                ],
                "example": "-- 3rd highest, window way\nSELECT salary FROM (\n  SELECT salary,\n    DENSE_RANK() OVER (ORDER BY salary DESC) AS rnk\n  FROM employees\n) t WHERE rnk = 3;\n\n-- classic way\nSELECT DISTINCT salary FROM employees e1\nWHERE 2 = (SELECT COUNT(DISTINCT salary)\n           FROM employees e2\n           WHERE e2.salary > e1.salary);",
                "answer": "Three ways: ORDER BY DESC with LIMIT 1 OFFSET n-1 on distinct salaries; DENSE_RANK over salary and pick rank n - the cleanest, and PARTITION BY extends it per department; or the correlated count subquery where n-1 distinct salaries are higher. I mention DENSE_RANK vs RANK for ties.",
            },
            {
                "title": "S5.6  SQL Injection and Prevention",
                "what": "SQL injection is when user input is glued into a query as text, letting an attacker change the query itself.",
                "points": [
                    "Example attack: input ' OR '1'='1 turns a login check into an always-true condition; '; DROP TABLE users;-- is the famous destructive form.",
                    "Root cause: string concatenation of untrusted input into SQL.",
                    "Fix #1 - parameterized queries / prepared statements: the query has placeholders (%s, ?), values travel separately and are never parsed as SQL. This alone kills injection.",
                    "Fix #2 - ORMs (Django ORM, SQLAlchemy) parameterize automatically - but raw() / text() fragments can still be vulnerable.",
                    "Defense in depth: validate input types, least-privilege DB user (app user cannot DROP), no raw DB errors shown to users.",
                    "Golden rule: NEVER f-string or concatenate user input into SQL - not even once.",
                ],
                "example": "# vulnerable\ncur.execute(f\"SELECT * FROM users WHERE name='{name}'\")\n# safe - parameterized\ncur.execute(\"SELECT * FROM users WHERE name = %s\", (name,))",
                "answer": "Injection happens when user input is concatenated into SQL, letting attackers inject conditions or commands. The real fix is parameterized queries - placeholders with values sent separately - which ORMs do by default; plus least-privilege DB accounts and input validation as depth.",
            },
            {
                "title": "S5.7  Query Optimization Tips",
                "what": "Most slow queries are fixed by reading the execution plan, indexing the right columns, and asking for less data.",
                "points": [
                    "Start with EXPLAIN / EXPLAIN ANALYZE - find full table scans, bad join order, missing index usage.",
                    "Index columns used in WHERE, JOIN, ORDER BY - and respect the composite leftmost-prefix rule.",
                    "Do not defeat indexes: no functions on the column side, no leading-wildcard LIKE, matching data types in joins.",
                    "Select only needed columns - SELECT * drags wide rows through network and memory.",
                    "Filter early (WHERE before HAVING), paginate with keyset instead of huge OFFSETs.",
                    "Prefer EXISTS/JOIN over IN on big subqueries; prefer UNION ALL over UNION when duplicates cannot occur.",
                    "Batch big writes; for bulk deletes on huge tables consider chunks or TRUNCATE.",
                    "Beyond queries: connection pooling, caching hot reads (Redis), and periodic ANALYZE so the optimizer has fresh statistics.",
                ],
                "example": "EXPLAIN ANALYZE\nSELECT o.id, o.amount\nFROM orders o\nWHERE o.customer_id = 42\n  AND o.created_at >= '2026-01-01'\nORDER BY o.created_at DESC\nLIMIT 20;",
                "answer": "I start with EXPLAIN to spot full scans, add or fix indexes for WHERE/JOIN/ORDER BY, avoid index-killers like functions on columns and leading wildcards, select only needed columns, filter early, use keyset pagination, and add caching or pooling at the app layer when the query itself is already tight.",
            },
            {
                "title": "S5.8  OLTP vs OLAP",
                "what": "OLTP systems run the business (many small fast transactions); OLAP systems analyze it (few heavy read queries over history).",
                "points": [
                    "OLTP: inserts/updates per order, per login - thousands per second, each touching a few rows. Normalized (3NF) schema, current data. Example: our shop's orders DB in MySQL/Postgres.",
                    "OLAP: \"revenue by category by month for 3 years\" - reads over millions of rows. Denormalized star schema (fact + dimension tables), historical data. Engines: warehouses like BigQuery, Redshift, Snowflake, ClickHouse.",
                    "OLTP measures transactions/sec and latency; OLAP measures query throughput over huge scans.",
                    "OLAP engines store data by COLUMN, which compresses well and reads only needed columns - that is why they scan billions fast.",
                    "Data flows OLTP -> (ETL/ELT pipeline) -> warehouse; running reports on the live OLTP DB slows real users.",
                    "Star schema: central fact table (sales) joined to dimensions (date, product, store).",
                ],
                "example": "-- OLTP: one order\nINSERT INTO orders (customer_id, amount) VALUES (42, 999);\n-- OLAP: 3-year trend\nSELECT d.year, p.category, SUM(f.amount)\nFROM sales_fact f\nJOIN dim_date d ON d.id = f.date_id\nJOIN dim_product p ON p.id = f.product_id\nGROUP BY d.year, p.category;",
                "answer": "OLTP handles many small real-time transactions on a normalized schema - the live business database. OLAP answers big analytical questions over history on denormalized, column-oriented warehouses like BigQuery or Redshift, fed by ETL from OLTP, so heavy reports never slow down real users.",
            },
        ],
    },
]
